// Gated on `__internals` — reaches into
// `crate::strategy_def_prototype` via the `__internals` re-export.
#![cfg(feature = "__internals")]
//! W44-192 — env-var fallback layer tests for the `strategy_def!`
//! macro prototype.
//!
//! Mirrors the production
//! [`tests/strategy_env_fallback.rs`](./strategy_env_fallback.rs) test
//! shape: a shared `std::sync::Mutex` serialises process-wide env-var
//! mutations across all tests in this binary so parallel `cargo test`
//! execution doesn't race on env var state. Each test snapshots the
//! two prototype-relevant env vars, runs its assertion, restores the
//! snapshot, releases the lock.
//!
//! The library carries `#![forbid(unsafe_code)]`, but each `tests/*.rs`
//! is its own crate root so we can perform the `unsafe { env::set_var }`
//! calls Rust 2024 requires.
//!
//! These tests verify the W44-192 prototype's
//! `apply_prototype_env_var_fallbacks` function — generated by the
//! `strategy_def!` macro — applies the env-var override **only** when
//! the resolved field equals its `Default::default()` value. Explicit
//! caller settings (via the per-strategy preset OR a `Custom` payload)
//! ALWAYS win over the env-var.
//!
//! Two env vars in scope:
//! - `JXL_W44_184_FORCE_LIBJXL_NEWTON=1` → `cfl_newton_libjxl_parity: bool`
//! - `JXL_W44_168_MODE=A|B|C|D` → `adaptive_buttloop_iters: IterMode`

use jxl_encoder::__internals::{PrototypeIterMode, resolve_prototype_strategy_named_for_test};

/// Names of the two env vars the W44-192 prototype reads. Order
/// matches the snapshot array order so callers can iterate `(name,
/// snapshot_value)` pairs deterministically.
const PROTOTYPE_ENV_VARS: [&str; 2] = ["JXL_W44_184_FORCE_LIBJXL_NEWTON", "JXL_W44_168_MODE"];

/// Shared lock serialising env-var mutations across all tests in
/// this binary. Mirrors the production W44_132_ENV_LOCK in
/// `strategy_env_fallback.rs`.
static W44_192_ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

fn env_lock_and_snapshot() -> (
    std::sync::MutexGuard<'static, ()>,
    [(&'static str, Option<String>); 2],
) {
    let guard = W44_192_ENV_LOCK
        .lock()
        .unwrap_or_else(|poison| poison.into_inner());
    let snapshot: [(&'static str, Option<String>); 2] = [
        (
            PROTOTYPE_ENV_VARS[0],
            std::env::var(PROTOTYPE_ENV_VARS[0]).ok(),
        ),
        (
            PROTOTYPE_ENV_VARS[1],
            std::env::var(PROTOTYPE_ENV_VARS[1]).ok(),
        ),
    ];
    for (name, _) in snapshot.iter() {
        // SAFETY: env mutation serialised by the W44_192_ENV_LOCK
        // mutex acquired above; no other thread is reading or writing
        // the JXL_* env vars while this guard is held.
        unsafe { std::env::remove_var(name) };
    }
    (guard, snapshot)
}

fn env_restore(snapshot: [(&'static str, Option<String>); 2]) {
    for (name, value) in snapshot.iter() {
        match value {
            // SAFETY: mutex still held by the test's `_guard` binding.
            Some(v) => unsafe { std::env::set_var(name, v) },
            // SAFETY: mutex still held by the test's `_guard` binding.
            None => unsafe { std::env::remove_var(name) },
        }
    }
}

/// With NO env vars set, every strategy resolves to its preset values.
/// Establishes the baseline against which env-var-induced changes are
/// measured.
#[test]
fn no_env_vars_default_passthrough() {
    let _env_serial = crate::env_serial();
    let (_guard, snapshot) = env_lock_and_snapshot();

    let (cfl, cca, iters) = resolve_prototype_strategy_named_for_test("Libjxl");
    assert!(cfl, "Libjxl preset: cfl_newton_libjxl_parity = true");
    assert!(!cca, "Libjxl preset: content_class_auto_classify = false");
    assert_eq!(iters, PrototypeIterMode::Off, "Libjxl preset: iters = Off");

    let (cfl, cca, iters) = resolve_prototype_strategy_named_for_test("Zenjxl");
    assert!(!cfl);
    assert!(cca);
    assert_eq!(iters, PrototypeIterMode::SmoothSkip);

    let (cfl, cca, iters) = resolve_prototype_strategy_named_for_test("LeanFaster");
    assert!(!cfl);
    assert!(!cca);
    assert_eq!(iters, PrototypeIterMode::Off);

    let (cfl, cca, iters) = resolve_prototype_strategy_named_for_test("Aggressive");
    assert!(!cfl);
    assert!(cca);
    assert_eq!(iters, PrototypeIterMode::SmoothSkip);

    env_restore(snapshot);
}

/// `JXL_W44_184_FORCE_LIBJXL_NEWTON=1` promotes `Zenjxl`'s
/// `cfl_newton_libjxl_parity` (= `false`, which equals
/// `bool::default()`) to `true`.
#[test]
fn env_cfl_newton_promotes_on_zenjxl() {
    let _env_serial = crate::env_serial();
    let (_guard, snapshot) = env_lock_and_snapshot();
    // SAFETY: env-var mutex is held.
    unsafe { std::env::set_var("JXL_W44_184_FORCE_LIBJXL_NEWTON", "1") };
    let (cfl, cca, iters) = resolve_prototype_strategy_named_for_test("Zenjxl");
    assert!(
        cfl,
        "env var promotes Zenjxl's default-`false` cfl_newton_libjxl_parity to true"
    );
    // Unrelated fields unchanged.
    assert!(cca);
    assert_eq!(iters, PrototypeIterMode::SmoothSkip);
    env_restore(snapshot);
}

/// `JXL_W44_184_FORCE_LIBJXL_NEWTON=1` is a no-op on `Libjxl` because
/// the preset already sets the field to `true` (which ≠
/// `bool::default()`). Documents the W44-132 short-circuit contract.
#[test]
fn env_cfl_newton_noop_on_libjxl() {
    let _env_serial = crate::env_serial();
    let (_guard, snapshot) = env_lock_and_snapshot();
    // SAFETY: env-var mutex is held.
    unsafe { std::env::set_var("JXL_W44_184_FORCE_LIBJXL_NEWTON", "1") };
    let (cfl, _, _) = resolve_prototype_strategy_named_for_test("Libjxl");
    assert!(cfl, "Libjxl already true — env-var is moot");
    env_restore(snapshot);
}

/// `JXL_W44_184_FORCE_LIBJXL_NEWTON=0` parses to `None` (the
/// `bool_one` parser only matches `"1"`), so the field stays at the
/// preset value. Documents the parser contract.
#[test]
fn env_cfl_newton_zero_does_not_flip() {
    let _env_serial = crate::env_serial();
    let (_guard, snapshot) = env_lock_and_snapshot();
    // SAFETY: env-var mutex is held.
    unsafe { std::env::set_var("JXL_W44_184_FORCE_LIBJXL_NEWTON", "0") };
    let (cfl, _, _) = resolve_prototype_strategy_named_for_test("Zenjxl");
    assert!(
        !cfl,
        "`0` does not parse as `Some(true)` — field stays at Zenjxl default false"
    );
    env_restore(snapshot);
}

/// `JXL_W44_168_MODE=C` on `Libjxl` (preset = `Off`, which equals
/// `IterMode::default()`) promotes the field to `TexturedExtend`.
#[test]
fn env_iter_mode_promotes_on_libjxl() {
    let _env_serial = crate::env_serial();
    let (_guard, snapshot) = env_lock_and_snapshot();
    // SAFETY: env-var mutex is held.
    unsafe { std::env::set_var("JXL_W44_168_MODE", "C") };
    let (_, _, iters) = resolve_prototype_strategy_named_for_test("Libjxl");
    assert_eq!(
        iters,
        PrototypeIterMode::TexturedExtend,
        "env var `C` parses to TexturedExtend; promotes default `Off`"
    );
    env_restore(snapshot);
}

/// `JXL_W44_168_MODE=C` is a no-op on `Zenjxl` because the preset
/// already sets `SmoothSkip` (≠ `IterMode::default()`).
#[test]
fn env_iter_mode_noop_on_zenjxl() {
    let _env_serial = crate::env_serial();
    let (_guard, snapshot) = env_lock_and_snapshot();
    // SAFETY: env-var mutex is held.
    unsafe { std::env::set_var("JXL_W44_168_MODE", "C") };
    let (_, _, iters) = resolve_prototype_strategy_named_for_test("Zenjxl");
    assert_eq!(
        iters,
        PrototypeIterMode::SmoothSkip,
        "Zenjxl preset SmoothSkip ≠ default Off; env-var is moot"
    );
    env_restore(snapshot);
}

/// Invalid env value: `JXL_W44_168_MODE=ZZ` — the parser returns
/// `None`, so the field stays at the preset (Off for Libjxl).
#[test]
fn env_iter_mode_invalid_value_noop() {
    let _env_serial = crate::env_serial();
    let (_guard, snapshot) = env_lock_and_snapshot();
    // SAFETY: env-var mutex is held.
    unsafe { std::env::set_var("JXL_W44_168_MODE", "ZZ") };
    let (_, _, iters) = resolve_prototype_strategy_named_for_test("Libjxl");
    assert_eq!(
        iters,
        PrototypeIterMode::Off,
        "invalid env value: parser returns None, field unchanged"
    );
    env_restore(snapshot);
}

/// All four enum letters parse correctly through the env hook on
/// `Libjxl` (preset = `Off` = default).
#[test]
fn env_iter_mode_all_letters_parse() {
    let _env_serial = crate::env_serial();
    let (_guard, snapshot) = env_lock_and_snapshot();
    for (letter, expected) in [
        ("A", PrototypeIterMode::Off),
        ("B", PrototypeIterMode::SmoothSkip),
        ("C", PrototypeIterMode::TexturedExtend),
        ("D", PrototypeIterMode::Combined),
    ] {
        // SAFETY: env-var mutex is held.
        unsafe { std::env::set_var("JXL_W44_168_MODE", letter) };
        let (_, _, iters) = resolve_prototype_strategy_named_for_test("Libjxl");
        assert_eq!(
            iters, expected,
            "letter `{letter}` should parse to {expected:?} on Libjxl preset (default Off)",
        );
    }
    env_restore(snapshot);
}

/// Both env vars set simultaneously: each fires independently on its
/// own gate.
#[test]
fn env_both_vars_independent() {
    let _env_serial = crate::env_serial();
    let (_guard, snapshot) = env_lock_and_snapshot();
    // SAFETY: env-var mutex is held.
    unsafe { std::env::set_var("JXL_W44_184_FORCE_LIBJXL_NEWTON", "1") };
    // SAFETY: env-var mutex is held.
    unsafe { std::env::set_var("JXL_W44_168_MODE", "D") };
    // Zenjxl (cfl=false=default, iters=SmoothSkip≠default):
    //   cfl flips to true; iters stays SmoothSkip.
    let (cfl, _, iters) = resolve_prototype_strategy_named_for_test("Zenjxl");
    assert!(cfl);
    assert_eq!(iters, PrototypeIterMode::SmoothSkip);
    // Libjxl (cfl=true≠default, iters=Off=default):
    //   cfl stays true; iters promotes to Combined.
    let (cfl, _, iters) = resolve_prototype_strategy_named_for_test("Libjxl");
    assert!(cfl);
    assert_eq!(iters, PrototypeIterMode::Combined);
    env_restore(snapshot);
}
