// Copyright (c) Imazen LLC and the JPEG XL Project Authors.
// Algorithms and constants derived from libjxl (BSD-3-Clause).
// Licensed under AGPL-3.0-or-later. Commercial licenses at https://www.imazen.io/pricing

//! Per-distance × per-display CVVDP JOD calibration table
//! (cvvdp-fork Phase 4 + Phase 2 display-config backfill).
//!
//! Phase 4 (2026-05-24) shipped the single-display SDR-200 table
//! (`vardct/cvvdp_targets.rs` initial commit — see
//! `docs/RFC_CVVDP_FORK.md` §2.1, §4 Phase 4 and
//! `docs/archive/RFC_CVVDP_PHASE4_BRIEF.md` Step 3).
//!
//! Phase 1 display-config backfill (2026-05-25, RFC
//! `docs/RFC_DISPLAY_CONFIG_BACKFILL.md`) extended the lookup to a
//! 3-row × 7-distance table covering [`crate::api::DisplayConfig`]'s
//! three Phase 1 variants. Phase 1 shipped heuristic seeds for Phone +
//! Tv (`WebSdr80 × {1.04, 1.12}`) gated on the upstream `CvvdpOpaque::new`
//! API which only accepted `DisplayModel` (not `DisplayGeometry`).
//!
//! **Phase 2 (2026-05-26)** lands the measured per-display tables:
//!
//! - [`crate::api::DisplayConfig::WebSdr80`] — preserved bit-identical
//!   from the Phase 4 seed (the legacy single-table values). Maps to
//!   `cvvdp_gpu::params::DisplayModel::STANDARD_4K` (200 cd/m² sRGB
//!   BT.709 at 250 lux ambient) + `DisplayGeometry::STANDARD_4K`
//!   (PPD ≈ 75.4).
//! - [`crate::api::DisplayConfig::Phone`] — 1000 cd/m² sustained-EDR
//!   sRGB Display-P3 at 200 lux indoor bright. Maps to a custom
//!   `DisplayModel` (built inline in [`crate::api::DisplayConfig::display_model`])
//!   + `DisplayGeometry::from_inches(2868, 1320, 11.8, 6.9)` (PPD ≈ 95).
//! - [`crate::api::DisplayConfig::Tv`] — `LG_OLED_2026_HDR_PQ` (3000
//!   cd/m² PQ BT.2020 at 5 lux dim) + `DisplayGeometry::LG_OLED_2026`.
//!
//! ## Purpose
//!
//! When the buttloop runs with the [GPU CVVDP backend] active, the
//! per-iter compare returns `score = (10.0 - JOD).clamp(0.0, 10.0)`
//! (mapped from cvvdp-gpu's native JOD ∈ [0, 10] where 10 = identical).
//! The buttloop's pre-existing convergence machinery consumes a
//! `target_distance` in butteraugli units (smaller = better, ~ [0, 5]
//! typical band). To keep the comparison surface coherent across
//! backends, when cvvdp is active the loop substitutes a
//! **cvvdp-native target** (in `score = 10 - JOD` space) interpolated
//! from this table at the caller-requested butteraugli `target_distance`
//! AND at the caller-requested [`crate::api::DisplayConfig`].
//!
//! [GPU CVVDP backend]: super::cvvdp_backend::gpu::GpuCvvdpBackend
//!
//! ## Phase 2 seed methodology — measured per-display tables
//!
//! Source: `benchmarks/cvvdp_per_display_reseed_2026-05-26.tsv` (3,402
//! rows: 1,134 unique cells × 3 displays). Generated by re-scoring
//! every (image, distance, effort) cell from Phase 1's tracking corpus
//! (`benchmarks/cvvdp_vs_buttloop_tracking_2026-05-24.tsv`, backend=B
//! rows) against the reference image under each of the three
//! `DisplayConfig`s. The CvvdpOpaque instance was constructed via
//! `CvvdpOpaque::new_with_geometry` (cvvdp_gpu master `a4994bb4`+) so
//! both the photometric AND geometric axes dispatch correctly per
//! display.
//!
//! Aggregation at `benchmarks/cvvdp_per_display_reseed_medians_2026-05-26.tsv`
//! collapses the n=162 scoring rows per (distance, display) into p25 /
//! p50 / p75 of `cvvdp_jod`. The per-distance medians are then
//! converted to butteraugli-direction `target = (10.0 - JOD_p50) × 1.05`
//! — the 1.05× tightening biases the cvvdp-driven loop to converge
//! slightly more strictly than what the butteraugli-driven baseline
//! achieves at the same nominal distance (matching Phase 4 methodology).
//!
//! ### Measured shifts vs Phase 1 heuristic
//!
//! Phase 1 modelled `Phone = WebSdr80 × 1.04` and `Tv = WebSdr80 × 1.12`
//! uniformly across distance. Measurement on the 1,134-cell corpus
//! shows the per-display Δ is STRONGLY distance-dependent — much
//! larger than the heuristic at low distance, smaller at high
//! distance (the Phone/Web ratio decreases from 2.91× at d=0.5 to
//! 1.06× at d=5.0; Tv/Web from 20.76× at d=0.5 to 1.79× at d=5.0).
//! A single global multiplier cannot capture this; Phase 2 ships
//! explicit per-distance arrays.
//!
//! Direction confirms the heuristic: `Tv > Phone > WebSdr80` at every
//! distance band. Magnitudes do not. The previously-documented per-row
//! 4% / 12% deltas are obsolete (left in `docs/RFC_DISPLAY_CONFIG_BACKFILL.md`
//! §7 commentary only).
//!
//! ### WebSdr80 measurement vs Phase 4 legacy
//!
//! The Phase 2 sweep measured WebSdr80 medians within ~3% of the
//! Phase 4 legacy values (`0.0025 / 0.0217 / 0.0454 / 0.0717 / 0.1318
//! / 0.2105 / 0.2966` measured vs `0.0029 / 0.0238 / 0.0461 / 0.0724
//! / 0.1336 / 0.2149 / 0.3005` legacy). The variance is from
//! corpus-composition differences between the Phase 4 baseline
//! (single-pass on the tracking sweep with mixed effort counts +
//! butteraugli-default cells) and this Phase 2 re-score (162 rows ×
//! 7 distances, all backend=B). The WebSdr80 row below is PINNED at
//! the Phase 4 legacy values exactly to preserve the byte-identity
//! invariant of the pre-Phase-1 single-table path; the
//! `websdr80_byte_identical_to_legacy_wrapper` unit test enforces
//! this.
//!
//! ## Monotonicity invariants
//!
//! - Within each row (display): targets grow with distance (stricter
//!   distance ⇒ larger acceptable cvvdp score).
//! - At each distance: `Tv >= Phone >= WebSdr80` (more luminance ⇒
//!   stricter convergence requirement). Holds on every measured cell
//!   in Phase 2.
//!
//! Both invariants are pinned by unit tests in `tests` module below.
//!
//! ## Linear interpolation
//!
//! [`cvvdp_target_score_for_distance_and_display`] interpolates
//! linearly between adjacent table points (within a row) and clamps
//! outside the band (`[0.50, 5.00]`). The table is monotone (target
//! grows with distance) so interpolation is well-defined per row.

use crate::api::DisplayConfig;

/// Number of distance bands in the per-display table. Pinned at 7 to
/// match the Phase 4 seed (d ∈ {0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0});
/// changing this requires a re-seed and per-display refit.
pub(crate) const CVVDP_DISTANCE_BANDS: usize = 7;

/// Per-display calibration row: distance / target pairs at the 7
/// canonical bands. Within-row monotone ascending in distance AND in
/// target score.
#[derive(Copy, Clone, Debug)]
pub(crate) struct DisplayCalibration {
    /// Display this row was calibrated for.
    pub(crate) display: DisplayConfig,
    /// 7 `(distance, target_score)` pairs.
    pub(crate) entries: [(f32, f32); CVVDP_DISTANCE_BANDS],
}

/// WebSdr80 row — PINNED at the Phase 4 legacy values to preserve the
/// byte-identity invariant of the pre-Phase-1 single-table path. See
/// module doc §"WebSdr80 measurement vs Phase 4 legacy" for why we
/// don't overwrite this with the Phase 2 measurement (the variance is
/// ~3% and the byte-identity invariant is load-bearing).
pub(crate) const WEB_SDR_80_TARGETS_BY_DISTANCE: [f32; 7] = [
    0.0029, // d=0.5  (Phase 4 legacy; Phase 2 measured 0.0025, n=162)
    0.0238, // d=1.0  (Phase 4 legacy; Phase 2 measured 0.0217, n=162)
    0.0461, // d=1.5  (Phase 4 legacy; Phase 2 measured 0.0454, n=162)
    0.0724, // d=2.0  (Phase 4 legacy; Phase 2 measured 0.0717, n=162)
    0.1336, // d=3.0  (Phase 4 legacy; Phase 2 measured 0.1318, n=162)
    0.2149, // d=4.0  (Phase 4 legacy; Phase 2 measured 0.2105, n=162)
    0.3005, // d=5.0  (Phase 4 legacy; Phase 2 measured 0.2966, n=162)
];

/// Phone row — measured from `benchmarks/cvvdp_per_display_reseed_2026-05-26.tsv`
/// medians of `cvvdp_jod` per distance (n=162 per bucket) under
/// `DisplayModel::Phone` + `DisplayGeometry::from_inches(2868, 1320,
/// 11.8, 6.9)` (PPD ≈ 95). Converted to `(10.0 - jod_p50) × 1.05`.
///
/// Phone/WebSdr80 ratio decreases with distance (2.91× at d=0.5 →
/// 1.06× at d=5.0); see module doc §"Measured shifts vs Phase 1
/// heuristic" for the structural explanation.
pub(crate) const PHONE_TARGETS_BY_DISTANCE: [f32; 7] = [
    0.0072, // d=0.5, n=162, median JOD=9.993102
    0.0370, // d=1.0, n=162, median JOD=9.964800
    0.0623, // d=1.5, n=162, median JOD=9.940644
    0.0962, // d=2.0, n=162, median JOD=9.908399
    0.1539, // d=3.0, n=162, median JOD=9.853419
    0.2344, // d=4.0, n=162, median JOD=9.776743
    0.3146, // d=5.0, n=162, median JOD=9.700408
];

/// Tv row — measured from `benchmarks/cvvdp_per_display_reseed_2026-05-26.tsv`
/// medians of `cvvdp_jod` per distance (n=162 per bucket) under
/// `DisplayModel::LG_OLED_2026_HDR_PQ` + `DisplayGeometry::LG_OLED_2026`.
/// Converted to `(10.0 - jod_p50) × 1.05`.
///
/// Tv/WebSdr80 ratio decreases with distance (20.76× at d=0.5 →
/// 1.79× at d=5.0). PQ EOTF + 3000 cd/m² peak + low ambient amplify
/// perceptible artifacts MUCH more than the Phase 1 heuristic
/// (uniform 1.12×) predicted — the low-distance amplification factor
/// was off by an order of magnitude on the heuristic.
pub(crate) const TV_TARGETS_BY_DISTANCE: [f32; 7] = [
    0.0517, // d=0.5, n=162, median JOD=9.950788
    0.1412, // d=1.0, n=162, median JOD=9.865481
    0.2002, // d=1.5, n=162, median JOD=9.809306
    0.2483, // d=2.0, n=162, median JOD=9.763523
    0.3429, // d=3.0, n=162, median JOD=9.673444
    0.4318, // d=4.0, n=162, median JOD=9.588735
    0.5310, // d=5.0, n=162, median JOD=9.494321
];

/// Canonical distance bands. Pinned at the 7 distances swept across
/// every Phase 1 / Phase 2 bench (matches Phase 4 seed).
pub(crate) const CVVDP_DISTANCE_VALUES: [f32; CVVDP_DISTANCE_BANDS] =
    [0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0];

/// WebSdr80 calibration row — pairs the Phase 4 legacy targets to
/// `CVVDP_DISTANCE_VALUES`.
pub(crate) const WEB_SDR_80_CALIBRATION: DisplayCalibration = DisplayCalibration {
    display: DisplayConfig::WebSdr80,
    entries: zip_entries(WEB_SDR_80_TARGETS_BY_DISTANCE),
};

/// Phone calibration row.
pub(crate) const PHONE_CALIBRATION: DisplayCalibration = DisplayCalibration {
    display: DisplayConfig::Phone,
    entries: zip_entries(PHONE_TARGETS_BY_DISTANCE),
};

/// Tv calibration row.
pub(crate) const TV_CALIBRATION: DisplayCalibration = DisplayCalibration {
    display: DisplayConfig::Tv,
    entries: zip_entries(TV_TARGETS_BY_DISTANCE),
};

/// Const helper: zip a per-distance target array with the canonical
/// distance bands.
const fn zip_entries(targets: [f32; CVVDP_DISTANCE_BANDS]) -> [(f32, f32); CVVDP_DISTANCE_BANDS] {
    let mut out = [(0.0, 0.0); CVVDP_DISTANCE_BANDS];
    let mut i = 0;
    while i < CVVDP_DISTANCE_BANDS {
        out[i] = (CVVDP_DISTANCE_VALUES[i], targets[i]);
        i += 1;
    }
    out
}

/// Lookup table indexed by display variant — same shape as the
/// upstream cvvdp-gpu preset surface. Adding a new
/// [`DisplayConfig`] variant requires adding a calibration row here.
pub(crate) static CVVDP_DISPLAY_CALIBRATIONS: &[DisplayCalibration] =
    &[WEB_SDR_80_CALIBRATION, PHONE_CALIBRATION, TV_CALIBRATION];

/// Legacy single-display per-distance table — same data as
/// [`WEB_SDR_80_CALIBRATION.entries`], kept as a const for use sites
/// that don't yet thread `DisplayConfig`. Phase 1+ callers should
/// prefer [`cvvdp_target_score_for_distance_and_display`].
///
/// Format: `(butteraugli_target_distance, cvvdp_target_score)`.
/// Table is sorted ascending by distance; lookup is linear interp +
/// clamp.
#[allow(dead_code)]
pub(crate) static CVVDP_DISTANCE_TARGETS: &[(f32, f32)] = &WEB_SDR_80_CALIBRATION.entries;

/// Look up the CVVDP `score = 10 - JOD` target for a given butteraugli
/// `target_distance` AND target [`DisplayConfig`]. Linear interpolation
/// between adjacent table points within the row; clamps to the boundary
/// value outside `[CVVDP_DISTANCE_TARGETS[0].0,
/// CVVDP_DISTANCE_TARGETS[last].0]`.
///
/// Returns the lookup value in score-direction (smaller = better),
/// directly comparable to the `BackendCompareResult::score` produced by
/// the cvvdp backends.
///
/// # Examples
///
/// ```ignore
/// use jxl_encoder::api::DisplayConfig;
/// // WebSdr80 d=1.0 returns the legacy 0.0238 (byte-identical to the
/// // pre-Phase-1 single-table lookup).
/// let s = cvvdp_target_score_for_distance_and_display(1.0, DisplayConfig::WebSdr80);
/// assert!((s - 0.0238).abs() < 1e-6);
///
/// // Phone target is strictly larger (tighter convergence).
/// let s_phone = cvvdp_target_score_for_distance_and_display(1.0, DisplayConfig::Phone);
/// assert!(s_phone > 0.0238);
/// // Tv target is strictly larger than Phone.
/// let s_tv = cvvdp_target_score_for_distance_and_display(1.0, DisplayConfig::Tv);
/// assert!(s_tv > s_phone);
/// ```
pub(crate) fn cvvdp_target_score_for_distance_and_display(
    target_distance: f32,
    display: DisplayConfig,
) -> f32 {
    let row = display_calibration(display);
    let table = &row.entries;
    // Below-band clamp.
    if target_distance <= table[0].0 {
        return table[0].1;
    }
    // Above-band clamp.
    let last = table.len() - 1;
    if target_distance >= table[last].0 {
        return table[last].1;
    }
    // Linear search — the table has 7 entries; binary search overhead
    // exceeds the per-call savings. Find the bracketing pair (d_lo, d_hi).
    for i in 0..last {
        let (d_lo, s_lo) = table[i];
        let (d_hi, s_hi) = table[i + 1];
        if target_distance >= d_lo && target_distance <= d_hi {
            // Linear interpolation: t ∈ [0, 1] between d_lo and d_hi.
            let span = d_hi - d_lo;
            if span <= 0.0 {
                return s_lo;
            }
            let t = (target_distance - d_lo) / span;
            return s_lo + t * (s_hi - s_lo);
        }
    }
    // Unreachable given the clamps above — keep a defensive fallback.
    table[last].1
}

/// Look up the CVVDP `score = 10 - JOD` target for a given butteraugli
/// `target_distance`, assuming [`DisplayConfig::WebSdr80`]. Thin wrapper
/// over [`cvvdp_target_score_for_distance_and_display`] preserved for
/// call sites that don't yet thread display config.
///
/// Byte-identical to the pre-Phase-1 lookup (the `WebSdr80` row IS the
/// Phase 4 seed table). All production callers have migrated to the
/// `_and_display` variant; this wrapper is retained as the API-stable
/// shim + the regression-test target for the `WebSdr80 == legacy`
/// byte-identity invariant.
#[allow(dead_code)]
pub(crate) fn cvvdp_target_score_for_distance(target_distance: f32) -> f32 {
    cvvdp_target_score_for_distance_and_display(target_distance, DisplayConfig::WebSdr80)
}

/// Find the per-display calibration row in
/// [`CVVDP_DISPLAY_CALIBRATIONS`]. Falls back to the WebSdr80 row if
/// the table is missing the variant — defensive: every variant in
/// [`DisplayConfig`] MUST have a calibration row (enforced by
/// `calibration_for_every_display_variant` test).
fn display_calibration(display: DisplayConfig) -> &'static DisplayCalibration {
    for row in CVVDP_DISPLAY_CALIBRATIONS {
        if row.display == display {
            return row;
        }
    }
    &WEB_SDR_80_CALIBRATION
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every row's distances are sorted ascending (required for linear-
    /// search bracketing).
    #[test]
    fn rows_sorted_ascending_by_distance() {
        for row in CVVDP_DISPLAY_CALIBRATIONS {
            for w in row.entries.windows(2) {
                assert!(
                    w[0].0 < w[1].0,
                    "{:?} row distances must be strictly ascending: {} >= {}",
                    row.display,
                    w[0].0,
                    w[1].0
                );
            }
        }
    }

    /// Each row is monotone ascending in target score: stricter
    /// distance implies a larger acceptable cvvdp score.
    #[test]
    fn cvvdp_target_score_per_display_is_monotone() {
        for row in CVVDP_DISPLAY_CALIBRATIONS {
            for w in row.entries.windows(2) {
                assert!(
                    w[0].1 <= w[1].1,
                    "{:?} target scores must be non-decreasing: {} > {}",
                    row.display,
                    w[0].1,
                    w[1].1
                );
            }
        }
    }

    /// At every distance, the Phone target is strictly larger than the
    /// WebSdr80 target (tighter convergence — Phone is more luminance-
    /// amplified per the Phase 2 measured table). Phase 2 measurement
    /// confirmed the heuristic's direction; magnitude is per-distance.
    #[test]
    fn cvvdp_target_score_phone_higher_than_websdr80() {
        for d_x100 in [50, 100, 150, 200, 300, 400, 500] {
            let d = (d_x100 as f32) * 0.01;
            let s_web = cvvdp_target_score_for_distance_and_display(d, DisplayConfig::WebSdr80);
            let s_phone = cvvdp_target_score_for_distance_and_display(d, DisplayConfig::Phone);
            assert!(
                s_phone > s_web,
                "at d={}, Phone target ({}) MUST be > WebSdr80 target ({}) — \
                 Phase 2 measured per-distance per-display table",
                d,
                s_phone,
                s_web
            );
        }
    }

    /// At every distance, the Tv target is strictly larger than the
    /// Phone target (Tv has higher peak luminance AND PQ EOTF AND lower
    /// ambient, all of which amplify perceptible artifacts).
    #[test]
    fn cvvdp_target_score_tv_higher_than_phone() {
        for d_x100 in [50, 100, 150, 200, 300, 400, 500] {
            let d = (d_x100 as f32) * 0.01;
            let s_phone = cvvdp_target_score_for_distance_and_display(d, DisplayConfig::Phone);
            let s_tv = cvvdp_target_score_for_distance_and_display(d, DisplayConfig::Tv);
            assert!(
                s_tv > s_phone,
                "at d={}, Tv target ({}) MUST be > Phone target ({}) — \
                 Tv has higher peak luminance, PQ EOTF, lower ambient",
                d,
                s_tv,
                s_phone
            );
        }
    }

    /// WebSdr80 lookup MUST be byte-identical to the legacy
    /// `cvvdp_target_score_for_distance(d)` wrapper (which routes
    /// through `display_calibration(WebSdr80)`) on every sweep point.
    #[test]
    fn websdr80_byte_identical_to_legacy_wrapper() {
        for d_x100 in 0..=600 {
            let d = (d_x100 as f32) * 0.01;
            let s_legacy = cvvdp_target_score_for_distance(d);
            let s_explicit =
                cvvdp_target_score_for_distance_and_display(d, DisplayConfig::WebSdr80);
            // bit-equal — wrapper just passes through.
            assert_eq!(
                s_legacy.to_bits(),
                s_explicit.to_bits(),
                "at d={}: legacy wrapper ({}) MUST equal explicit WebSdr80 ({}) bit-for-bit",
                d,
                s_legacy,
                s_explicit
            );
        }
    }

    /// WebSdr80 row endpoints MUST match the Phase 4 legacy values
    /// exactly. The byte-identity invariant for the pre-Phase-1
    /// single-table path depends on this; the Phase 2 sweep did NOT
    /// overwrite these even though its measurement differed slightly
    /// (~3% on each distance — within sweep variance, see module doc
    /// §"WebSdr80 measurement vs Phase 4 legacy" for the rationale).
    #[test]
    fn websdr80_row_pinned_to_phase4_legacy() {
        let phase4_legacy: [(f32, f32); 7] = [
            (0.50, 0.0029),
            (1.00, 0.0238),
            (1.50, 0.0461),
            (2.00, 0.0724),
            (3.00, 0.1336),
            (4.00, 0.2149),
            (5.00, 0.3005),
        ];
        for (i, &(d, expected)) in phase4_legacy.iter().enumerate() {
            let got = cvvdp_target_score_for_distance_and_display(d, DisplayConfig::WebSdr80);
            assert_eq!(
                got.to_bits(),
                expected.to_bits(),
                "WebSdr80 row[{}] at d={}: got {}, Phase 4 legacy expected {} — \
                 the byte-identity invariant requires this row stays pinned",
                i,
                d,
                got,
                expected
            );
        }
    }

    /// Every variant of [`DisplayConfig`] MUST have a calibration row.
    /// Guards against future enum extensions silently falling back to
    /// the WebSdr80 row.
    #[test]
    fn calibration_for_every_display_variant() {
        for display in [
            DisplayConfig::WebSdr80,
            DisplayConfig::Phone,
            DisplayConfig::Tv,
        ] {
            let found = CVVDP_DISPLAY_CALIBRATIONS
                .iter()
                .any(|r| r.display == display);
            assert!(
                found,
                "DisplayConfig::{:?} has no calibration row in \
                 CVVDP_DISPLAY_CALIBRATIONS — add one before shipping",
                display
            );
        }
    }

    /// Below-band clamp to the first entry of each row; above-band
    /// clamp to the last.
    #[test]
    fn lookup_outside_band_clamps_per_display() {
        for &display in &[
            DisplayConfig::WebSdr80,
            DisplayConfig::Phone,
            DisplayConfig::Tv,
        ] {
            let row = display_calibration(display);
            let first_v = row.entries[0].1;
            let last_v = row.entries[row.entries.len() - 1].1;
            assert!(
                (cvvdp_target_score_for_distance_and_display(0.0, display) - first_v).abs() < 1e-6
            );
            assert!(
                (cvvdp_target_score_for_distance_and_display(0.25, display) - first_v).abs() < 1e-6
            );
            assert!(
                (cvvdp_target_score_for_distance_and_display(10.0, display) - last_v).abs() < 1e-6
            );
            assert!(
                (cvvdp_target_score_for_distance_and_display(100.0, display) - last_v).abs() < 1e-6
            );
        }
    }

    /// Linear interpolation within each row.
    #[test]
    fn lookup_interpolates_linearly_per_display() {
        // Midpoint of (1.0, _) and (1.5, _) is at d=1.25.
        for &display in &[
            DisplayConfig::WebSdr80,
            DisplayConfig::Phone,
            DisplayConfig::Tv,
        ] {
            let row = display_calibration(display);
            let (s_1_0, s_1_5) = (row.entries[1].1, row.entries[2].1);
            let expected = (s_1_0 + s_1_5) * 0.5;
            let got = cvvdp_target_score_for_distance_and_display(1.25, display);
            assert!(
                (got - expected).abs() < 1e-4,
                "{:?} interp at d=1.25: got {} expected {}",
                display,
                got,
                expected
            );
        }
    }

    /// Endpoints return the table values exactly per row.
    #[test]
    fn lookup_endpoints_exact_per_display() {
        for &display in &[
            DisplayConfig::WebSdr80,
            DisplayConfig::Phone,
            DisplayConfig::Tv,
        ] {
            let row = display_calibration(display);
            let first = row.entries[0];
            let last = row.entries[row.entries.len() - 1];
            let s_first = cvvdp_target_score_for_distance_and_display(first.0, display);
            let s_last = cvvdp_target_score_for_distance_and_display(last.0, display);
            assert!(
                (s_first - first.1).abs() < 1e-6,
                "{:?} lookup at first entry must return its value",
                display
            );
            assert!(
                (s_last - last.1).abs() < 1e-6,
                "{:?} lookup at last entry must return its value",
                display
            );
        }
    }

    /// Lookup is finite, non-negative, and bounded across the band for
    /// every display variant. Tv at d=5.0 is the strictest (~0.531
    /// per Phase 2 measurement); 1.0 is the safe upper bound.
    #[test]
    fn lookup_well_behaved_across_band_per_display() {
        for &display in &[
            DisplayConfig::WebSdr80,
            DisplayConfig::Phone,
            DisplayConfig::Tv,
        ] {
            for d_x10 in 0..=60 {
                let d = (d_x10 as f32) * 0.1;
                let s = cvvdp_target_score_for_distance_and_display(d, display);
                assert!(
                    s.is_finite() && s >= 0.0,
                    "{:?} lookup at d={} returned {} (finite={}, >=0={})",
                    display,
                    d,
                    s,
                    s.is_finite(),
                    s >= 0.0
                );
                // Tv at d=5.0 is the strictest band entry (~0.531);
                // 1.0 is the safe upper bound for any sane distance.
                assert!(
                    s <= 1.0,
                    "{:?} lookup at d={} returned {} > 1.0",
                    display,
                    d,
                    s
                );
            }
        }
    }

    /// Each calibration row has exactly the 7 canonical bands.
    #[test]
    fn each_row_has_seven_entries() {
        for row in CVVDP_DISPLAY_CALIBRATIONS {
            assert_eq!(
                row.entries.len(),
                7,
                "{:?} row should have 7 entries (d ∈ {{0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0}})",
                row.display
            );
        }
    }

    /// Phase 2 honeypot: ensure the Phone + Tv tables stay in measured
    /// ranges per distance. If a future refit moves them outside these
    /// envelopes, the seed methodology section should be re-verified
    /// against the new sweep TSV.
    #[test]
    fn phase2_tables_in_measured_envelope() {
        // Phone targets should stay within ±40% of the Phase 2
        // measurement at every distance (allows for small refits but
        // catches accidental zeros / order-of-magnitude bugs).
        for (i, (got, base)) in PHONE_TARGETS_BY_DISTANCE
            .iter()
            .zip([0.0072_f32, 0.0370, 0.0623, 0.0962, 0.1539, 0.2344, 0.3146].iter())
            .enumerate()
        {
            let rel = (got - base).abs() / base;
            assert!(
                rel < 0.40,
                "PHONE_TARGETS_BY_DISTANCE[{i}] = {got} drifted >40% from Phase 2 measurement {base}; \
                 re-verify against benchmarks/cvvdp_per_display_reseed_*.tsv before shipping"
            );
        }
        for (i, (got, base)) in TV_TARGETS_BY_DISTANCE
            .iter()
            .zip([0.0517_f32, 0.1412, 0.2002, 0.2483, 0.3429, 0.4318, 0.5310].iter())
            .enumerate()
        {
            let rel = (got - base).abs() / base;
            assert!(
                rel < 0.40,
                "TV_TARGETS_BY_DISTANCE[{i}] = {got} drifted >40% from Phase 2 measurement {base}; \
                 re-verify against benchmarks/cvvdp_per_display_reseed_*.tsv before shipping"
            );
        }
        // Phone targets must all be strictly less than Tv targets at
        // the same index (per-distance Tv > Phone invariant).
        for i in 0..CVVDP_DISTANCE_BANDS {
            assert!(
                PHONE_TARGETS_BY_DISTANCE[i] < TV_TARGETS_BY_DISTANCE[i],
                "PHONE_TARGETS_BY_DISTANCE[{}]={} MUST be < TV_TARGETS_BY_DISTANCE[{}]={}",
                i,
                PHONE_TARGETS_BY_DISTANCE[i],
                i,
                TV_TARGETS_BY_DISTANCE[i]
            );
        }
        // Phone targets must all be strictly greater than the Phase 4
        // WebSdr80 legacy values at the same index.
        for i in 0..CVVDP_DISTANCE_BANDS {
            assert!(
                PHONE_TARGETS_BY_DISTANCE[i] > WEB_SDR_80_TARGETS_BY_DISTANCE[i],
                "PHONE_TARGETS_BY_DISTANCE[{}]={} MUST be > WEB_SDR_80_TARGETS_BY_DISTANCE[{}]={}",
                i,
                PHONE_TARGETS_BY_DISTANCE[i],
                i,
                WEB_SDR_80_TARGETS_BY_DISTANCE[i]
            );
        }
    }
}
