[profile.release]
debug = true

[profile.bench]
debug = true

[profile.test]
opt-level = 3

[profile.dev]
opt-level = 2

[workspace]
members = ["jxl-encoder", "jxl-encoder-cli", "jxl-encoder-simd"]
resolver = "2"

[workspace.lints.clippy]
missing_safety_doc = "deny"
undocumented_unsafe_blocks = "deny"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "AGPL-3.0-only OR LicenseRef-Imazen-Commercial"
repository = "https://github.com/imazen/jxl-encoder"
homepage = "https://github.com/imazen/jxl-encoder"
authors = ["Lilith River"]
rust-version = "1.89"
