// Copyright (c) the JPEG XL Project Authors. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//! Forward DCT transforms ported from libjxl-tiny.
//!
//! Implements the "Lowest Complexity Self Recursive Radix-2 DCT II/III
//! Algorithms" by Siriani M. Perera and Jianhua Liu.
//!
//! This is a scalar implementation that matches libjxl-tiny's output.

// Ported float constants from C++ - exact values are intentional for parity.
#![allow(clippy::excessive_precision)]
#![allow(clippy::approx_constant)]
#![allow(dead_code)]

// =============================================================================
// Constants from libjxl-tiny dct_scales.h
// IMPORTANT: These values are copied exactly from the C++ source.
// =============================================================================

/// sqrt(2) constant used in DCT
pub const SQRT2: f32 = 1.41421356237;

/// Multipliers for DCT computation.
/// Generated by: `1.0 / (2 * cos((i + 0.5) * pi / N))` for i in 0..N/2
// Copied directly from libjxl-tiny dct_scales.h
pub const WC_MULTIPLIERS_4: [f32; 2] = [0.541196100146197, 1.3065629648763764];

// Copied directly from libjxl-tiny dct_scales.h
pub const WC_MULTIPLIERS_8: [f32; 4] = [
    0.5097955791041592,
    0.6013448869350453,
    0.8999762231364156,
    2.5629154477415055,
];

// Copied directly from libjxl-tiny dct_scales.h
pub const WC_MULTIPLIERS_16: [f32; 8] = [
    0.5024192861881557,
    0.5224986149396889,
    0.5669440348163577,
    0.6468217833599901,
    0.7881546234512502,
    1.060677685990347,
    1.7224470982383342,
    5.101148618689155,
];

/// Resample scales for DC extraction from larger DCTs.
// Copied directly from libjxl-tiny dct_scales.h
pub const DCT_RESAMPLE_SCALE_16_TO_2: [f32; 2] = [1.000000000000000000, 0.901764195028874394];

pub const DCT_RESAMPLE_SCALE_2_TO_16: [f32; 2] = [1.000000000000000000, 1.108937353592731823];

// =============================================================================
// DCT Algorithm Implementation
// =============================================================================

/// In-place 1D DCT for N=2
#[inline]
fn dct1d_2(mem: &mut [f32]) {
    let in1 = mem[0];
    let in2 = mem[1];
    mem[0] = in1 + in2;
    mem[1] = in1 - in2;
}

/// In-place 1D DCT for N=4
fn dct1d_4(mem: &mut [f32]) {
    // AddReverse: tmp[i] = mem[i] + mem[N-1-i] for first half
    // SubReverse: tmp[N/2+i] = mem[i] - mem[N-1-i] for second half
    let mut tmp = [0.0f32; 4];
    tmp[0] = mem[0] + mem[3];
    tmp[1] = mem[1] + mem[2];
    tmp[2] = mem[0] - mem[3];
    tmp[3] = mem[1] - mem[2];

    // DCT on first half
    dct1d_2(&mut tmp[0..2]);

    // Multiply second half by WcMultipliers
    tmp[2] *= WC_MULTIPLIERS_4[0];
    tmp[3] *= WC_MULTIPLIERS_4[1];

    // DCT on second half
    dct1d_2(&mut tmp[2..4]);

    // B transform on second half
    // B: tmp[0] = sqrt2 * tmp[0] + tmp[1], then tmp[i] = tmp[i] + tmp[i+1] for rest
    tmp[2] = SQRT2 * tmp[2] + tmp[3];
    // (no more elements for N/2=2)

    // InverseEvenOdd: interleave even and odd
    mem[0] = tmp[0];
    mem[2] = tmp[1];
    mem[1] = tmp[2];
    mem[3] = tmp[3];
}

/// In-place 1D DCT for N=8
fn dct1d_8(mem: &mut [f32]) {
    let mut tmp = [0.0f32; 8];

    // AddReverse for first half
    for i in 0..4 {
        tmp[i] = mem[i] + mem[7 - i];
    }
    // SubReverse for second half
    for i in 0..4 {
        tmp[4 + i] = mem[i] - mem[7 - i];
    }

    // DCT on first half
    dct1d_4(&mut tmp[0..4]);

    // Multiply second half by WcMultipliers
    for i in 0..4 {
        tmp[4 + i] *= WC_MULTIPLIERS_8[i];
    }

    // DCT on second half
    dct1d_4(&mut tmp[4..8]);

    // B transform on second half
    tmp[4] = SQRT2 * tmp[4] + tmp[5];
    tmp[5] += tmp[6];
    tmp[6] += tmp[7];

    // InverseEvenOdd: interleave
    for i in 0..4 {
        mem[2 * i] = tmp[i];
        mem[2 * i + 1] = tmp[4 + i];
    }
}

/// In-place 1D DCT for N=16
fn dct1d_16(mem: &mut [f32]) {
    let mut tmp = [0.0f32; 16];

    // AddReverse for first half
    for i in 0..8 {
        tmp[i] = mem[i] + mem[15 - i];
    }
    // SubReverse for second half
    for i in 0..8 {
        tmp[8 + i] = mem[i] - mem[15 - i];
    }

    // DCT on first half
    dct1d_8(&mut tmp[0..8]);

    // Multiply second half by WcMultipliers
    for i in 0..8 {
        tmp[8 + i] *= WC_MULTIPLIERS_16[i];
    }

    // DCT on second half
    dct1d_8(&mut tmp[8..16]);

    // B transform on second half
    tmp[8] = SQRT2 * tmp[8] + tmp[9];
    for i in 1..7 {
        tmp[8 + i] += tmp[8 + i + 1];
    }

    // InverseEvenOdd: interleave
    for i in 0..8 {
        mem[2 * i] = tmp[i];
        mem[2 * i + 1] = tmp[8 + i];
    }
}

/// Transpose an NxM block in-place (actually copies to output).
fn transpose<const N: usize, const M: usize>(input: &[f32], output: &mut [f32]) {
    for row in 0..N {
        for col in 0..M {
            output[col * N + row] = input[row * M + col];
        }
    }
}

/// Compute scaled 8x8 DCT.
///
/// Input: 8x8 block in row-major order
/// Output: 8x8 DCT coefficients in **transposed** layout
///
/// IMPORTANT: libjxl-tiny's ComputeScaledDCT does NOT transpose back for square blocks.
/// The decoder expects coefficients in this transposed layout. For 8x8 blocks,
/// output[cx * 8 + cy] contains the coefficient for frequency (cy, cx) where
/// cy is the vertical frequency and cx is the horizontal frequency.
pub fn dct_8x8(input: &[f32; 64], output: &mut [f32; 64]) {
    let mut tmp = [0.0f32; 64];

    // Transform rows
    for row in 0..8 {
        let row_start = row * 8;
        tmp[row_start..row_start + 8].copy_from_slice(&input[row_start..row_start + 8]);
        dct1d_8(&mut tmp[row_start..row_start + 8]);
        // Scale by 1/N
        for i in 0..8 {
            tmp[row_start + i] *= 1.0 / 8.0;
        }
    }

    // Transpose
    let mut transposed = [0.0f32; 64];
    transpose::<8, 8>(&tmp, &mut transposed);

    // Transform columns (now rows after transpose)
    for row in 0..8 {
        let row_start = row * 8;
        dct1d_8(&mut transposed[row_start..row_start + 8]);
        // Scale by 1/N
        for i in 0..8 {
            transposed[row_start + i] *= 1.0 / 8.0;
        }
    }

    // DO NOT transpose back! libjxl-tiny expects transposed output for square blocks.
    // This matches ComputeScaledDCT in libjxl-tiny/encoder/enc_transforms-inl.h
    output.copy_from_slice(&transposed);
}

/// Compute scaled 16x8 DCT (16 rows, 8 columns).
///
/// Input: 16x8 block in row-major order (128 floats)
/// Output: 16x8 DCT coefficients
pub fn dct_16x8(input: &[f32; 128], output: &mut [f32; 128]) {
    let mut tmp = [0.0f32; 128];

    // Transform rows (8 columns each)
    for row in 0..16 {
        let row_start = row * 8;
        tmp[row_start..row_start + 8].copy_from_slice(&input[row_start..row_start + 8]);
        dct1d_8(&mut tmp[row_start..row_start + 8]);
        for i in 0..8 {
            tmp[row_start + i] *= 1.0 / 8.0;
        }
    }

    // Transpose 16x8 -> 8x16
    let mut transposed = [0.0f32; 128];
    for row in 0..16 {
        for col in 0..8 {
            transposed[col * 16 + row] = tmp[row * 8 + col];
        }
    }

    // Transform columns (now 16 elements each)
    for row in 0..8 {
        let row_start = row * 16;
        dct1d_16(&mut transposed[row_start..row_start + 16]);
        for i in 0..16 {
            transposed[row_start + i] *= 1.0 / 16.0;
        }
    }

    // No final transpose — C++ ComputeScaledDCT<16,8> (ROWS >= COLS branch)
    // does not include a final transpose, matching DCT8x8 behavior.
    // Output is in 8x16 layout: output[fx * 16 + fy] for frequency (fy, fx).
    output.copy_from_slice(&transposed);
}

/// Compute scaled 8x16 DCT (8 rows, 16 columns).
///
/// Input: 8x16 block in row-major order (128 floats)
/// Output: 8x16 DCT coefficients
pub fn dct_8x16(input: &[f32; 128], output: &mut [f32; 128]) {
    let mut tmp = [0.0f32; 128];

    // Transform rows (16 columns each)
    for row in 0..8 {
        let row_start = row * 16;
        tmp[row_start..row_start + 16].copy_from_slice(&input[row_start..row_start + 16]);
        dct1d_16(&mut tmp[row_start..row_start + 16]);
        for i in 0..16 {
            tmp[row_start + i] *= 1.0 / 16.0;
        }
    }

    // Transpose 8x16 -> 16x8
    let mut transposed = [0.0f32; 128];
    for row in 0..8 {
        for col in 0..16 {
            transposed[col * 8 + row] = tmp[row * 16 + col];
        }
    }

    // Transform columns (now 8 elements each)
    for row in 0..16 {
        let row_start = row * 8;
        dct1d_8(&mut transposed[row_start..row_start + 8]);
        for i in 0..8 {
            transposed[row_start + i] *= 1.0 / 8.0;
        }
    }

    // Transpose 16x8 -> 8x16
    for row in 0..16 {
        for col in 0..8 {
            output[col * 16 + row] = transposed[row * 8 + col];
        }
    }
}

/// Compute scaled 16x16 DCT (16 rows, 16 columns).
///
/// Input: 16x16 block in row-major order (256 floats)
/// Output: 16x16 DCT coefficients
///
/// Like `dct_8x8()`, there is NO final transpose for square blocks.
/// C++ `ComputeScaledDCT<16,16>` takes the ROWS >= COLS branch (no final transpose).
pub fn dct_16x16(input: &[f32; 256], output: &mut [f32; 256]) {
    let mut tmp = [0.0f32; 256];

    // Transform rows (16 columns each)
    for row in 0..16 {
        let row_start = row * 16;
        tmp[row_start..row_start + 16].copy_from_slice(&input[row_start..row_start + 16]);
        dct1d_16(&mut tmp[row_start..row_start + 16]);
        // Scale by 1/N
        for i in 0..16 {
            tmp[row_start + i] *= 1.0 / 16.0;
        }
    }

    // Transpose 16x16
    let mut transposed = [0.0f32; 256];
    transpose::<16, 16>(&tmp, &mut transposed);

    // Transform columns (now rows after transpose)
    for row in 0..16 {
        let row_start = row * 16;
        dct1d_16(&mut transposed[row_start..row_start + 16]);
        // Scale by 1/N
        for i in 0..16 {
            transposed[row_start + i] *= 1.0 / 16.0;
        }
    }

    // DO NOT transpose back! Same as DCT8x8 - square blocks stay transposed.
    output.copy_from_slice(&transposed);
}

/// Extract DC values from 16x16 DCT coefficients.
/// Returns 4 DC values (for the 4 covered 8x8 blocks) in order [dc00, dc01, dc10, dc11].
///
/// The LLF region is 2x2 coefficients at positions [0, 1, 16, 17] in the 16x16 layout
/// (stride 16). We apply `DCTTotalResampleScale<16, 2>` to each dimension, then a
/// 2x2 IDCT to get the 4 DC values.
///
/// C++ uses `ReinterpretingIDCT<16, 16, 2, 2, 2, 2>` with the ROWS >= COLS branch
/// (since ROWS=COLS=2), which reads LLF in (y, x) = (0..LF_COLS, 0..LF_ROWS) order.
pub fn dc_from_dct_16x16(coeffs: &[f32; 256]) -> [f32; 4] {
    let s0 = DCT_RESAMPLE_SCALE_16_TO_2[0]; // 1.0
    let s1 = DCT_RESAMPLE_SCALE_16_TO_2[1]; // 0.9018...

    // Read LLF 2x2 from positions [0, 1, 16, 17] and apply resample scales.
    // C++ ROWS >= COLS branch: block[y * ROWS + x] = input[y * stride + x] * scale_col[y] * scale_row[x]
    // For 16x16 (ROWS=COLS=2): scale_col = scale_row = DCTTotalResampleScale<16,2>
    let b00 = coeffs[0] * s0 * s0;
    let b10 = coeffs[1] * s1 * s0; // block[0*2+1]  = input[0*16+1] * s0 * s1 -- but C++ has [y*R+x] = [y*stride+x]*s_c(y)*s_r(x)
    let b01 = coeffs[16] * s0 * s1; // block[1*2+0] = input[1*16+0] * s1 * s0
    let b11 = coeffs[17] * s1 * s1;

    // 2x2 IDCT (ComputeScaledIDCT<2,2>):
    // For 2-point IDCT: [a, b] -> [a+b, a-b]
    // Apply to rows then columns:
    // Row 0: [b00+b10, b00-b10]
    // Row 1: [b01+b11, b01-b11]
    // Column 0: [(b00+b10)+(b01+b11), (b00+b10)-(b01+b11)]
    // Column 1: [(b00-b10)+(b01-b11), (b00-b10)-(b01-b11)]
    let dc00 = (b00 + b10) + (b01 + b11);
    let dc01 = (b00 - b10) + (b01 - b11);
    let dc10 = (b00 + b10) - (b01 + b11);
    let dc11 = (b00 - b10) - (b01 - b11);

    [dc00, dc01, dc10, dc11]
}

/// Extract DC value from 8x8 DCT coefficients.
/// For DCT8, DC is just the [0,0] coefficient.
#[inline]
pub fn dc_from_dct_8x8(coeffs: &[f32; 64]) -> f32 {
    coeffs[0]
}

/// Extract DC values from 16x8 DCT coefficients.
/// Returns 2 DC values (for the 2 covered 8x8 blocks).
///
/// Uses ReinterpretingIDCT to convert LF coefficients to DC.
pub fn dc_from_dct_16x8(coeffs: &[f32; 128]) -> [f32; 2] {
    // For 16x8, the LF region is 2x1 coefficients (2 rows, 1 col in freq domain)
    // In the 8×16 output layout (stride 16), both LLF coefficients are at indices 0 and 1.
    //
    // C++ DCFromLowestFrequencies uses DCTTotalResampleScale<16, 2> (forward direction:
    // FROM 16-point DCT TO 2-point domain). Must use 16_TO_2 scales, NOT 2_TO_16.
    let lf0 = coeffs[0] * DCT_RESAMPLE_SCALE_16_TO_2[0];
    let lf1 = coeffs[1] * DCT_RESAMPLE_SCALE_16_TO_2[1];

    // 2-point IDCT: [a+b, a-b]
    [lf0 + lf1, lf0 - lf1]
}

/// Extract DC values from 8x16 DCT coefficients.
/// Returns 2 DC values (for the 2 covered 8x8 blocks).
pub fn dc_from_dct_8x16(coeffs: &[f32; 128]) -> [f32; 2] {
    // For 8x16, the LF region is 1x2 coefficients
    // Uses 16_TO_2 direction (FROM 16-point DCT TO 2-point domain).
    let lf0 = coeffs[0] * DCT_RESAMPLE_SCALE_16_TO_2[0];
    let lf1 = coeffs[1] * DCT_RESAMPLE_SCALE_16_TO_2[1];

    // 2-point IDCT: [a+b, a-b]
    [lf0 + lf1, lf0 - lf1]
}

// =============================================================================
// DCT32x32 support
// =============================================================================

/// WC multipliers for N=32.
/// Generated by: `1.0 / (2 * cos((i + 0.5) * pi / 32))` for i in 0..16.
/// Copied from libjxl dct_scales.h.
pub const WC_MULTIPLIERS_32: [f32; 16] = [
    0.5006029982351963,
    0.5054709598975436,
    0.5154473099226246,
    0.5310425910897841,
    0.5531038960344445,
    0.5829349682061339,
    0.6225041230356648,
    0.6748083414550057,
    0.7445362710022986,
    0.8393496454155268,
    0.9725682378619608,
    1.1694399334328847,
    1.4841646163141662,
    2.057781009953411,
    3.407608418468719,
    10.190008123548033,
];

/// Resample scales for DC extraction from 32-point DCT to 4-point domain.
/// DCTTotalResampleScale<32, 4> from libjxl.
pub const DCT_RESAMPLE_SCALE_32_TO_4: [f32; 4] = [
    1.0,
    0.974886821136879522,
    0.901764195028874394,
    0.787054918159101335,
];

/// In-place 1D DCT for N=32
fn dct1d_32(mem: &mut [f32]) {
    let mut tmp = [0.0f32; 32];

    // AddReverse for first half
    for i in 0..16 {
        tmp[i] = mem[i] + mem[31 - i];
    }
    // SubReverse for second half
    for i in 0..16 {
        tmp[16 + i] = mem[i] - mem[31 - i];
    }

    // DCT on first half
    dct1d_16(&mut tmp[0..16]);

    // Multiply second half by WcMultipliers
    for i in 0..16 {
        tmp[16 + i] *= WC_MULTIPLIERS_32[i];
    }

    // DCT on second half
    dct1d_16(&mut tmp[16..32]);

    // B transform on second half
    tmp[16] = SQRT2 * tmp[16] + tmp[17];
    for i in 1..15 {
        tmp[16 + i] += tmp[16 + i + 1];
    }

    // InverseEvenOdd: interleave
    for i in 0..16 {
        mem[2 * i] = tmp[i];
        mem[2 * i + 1] = tmp[16 + i];
    }
}

/// Compute scaled 32x32 DCT (32 rows, 32 columns).
///
/// Input: 32x32 block in row-major order (1024 floats)
/// Output: 32x32 DCT coefficients
///
/// Like `dct_8x8()` and `dct_16x16()`, there is NO final transpose for square blocks.
/// C++ `ComputeScaledDCT<32,32>` takes the ROWS >= COLS branch (no final transpose).
pub fn dct_32x32(input: &[f32; 1024], output: &mut [f32; 1024]) {
    let mut tmp = [0.0f32; 1024];

    // Transform rows (32 columns each)
    for row in 0..32 {
        let row_start = row * 32;
        tmp[row_start..row_start + 32].copy_from_slice(&input[row_start..row_start + 32]);
        dct1d_32(&mut tmp[row_start..row_start + 32]);
        // Scale by 1/N
        for i in 0..32 {
            tmp[row_start + i] *= 1.0 / 32.0;
        }
    }

    // Transpose 32x32
    let mut transposed = [0.0f32; 1024];
    transpose::<32, 32>(&tmp, &mut transposed);

    // Transform columns (now rows after transpose)
    for row in 0..32 {
        let row_start = row * 32;
        dct1d_32(&mut transposed[row_start..row_start + 32]);
        // Scale by 1/N
        for i in 0..32 {
            transposed[row_start + i] *= 1.0 / 32.0;
        }
    }

    // DO NOT transpose back! Same as DCT8x8/DCT16x16 - square blocks stay transposed.
    output.copy_from_slice(&transposed);
}

/// 4-point inverse DCT (type-III).
///
/// Direct formula implementation for the 4-point IDCT used in DC extraction.
/// Input: 4 frequency-domain coefficients, Output: 4 spatial-domain values.
fn idct1d_4(input: &[f32; 4], output: &mut [f32; 4]) {
    // The unnormalized type-III DCT of length 4:
    // X[k] = x[0] + sum_{n=1..3} x[n] * 2 * cos(pi * n * (2k+1) / 8) for k=0..3
    //
    // We use the butterfly decomposition matching libjxl's ComputeScaledIDCT:
    // Stage 1: B-transform (reverse of forward B-transform)
    // Stage 2: EvenOdd separation
    // Stage 3: WC multiply
    // Stage 4: IDCT on halves
    // Stage 5: AddSubReverse

    // For 4-point: direct computation is clearest.
    // cos(pi/8) = cos(22.5°), cos(3pi/8) = cos(67.5°)
    let c1 = core::f32::consts::FRAC_PI_8.cos(); // cos(pi/8) ≈ 0.9239
    let c3 = (3.0 * core::f32::consts::FRAC_PI_8).cos(); // cos(3pi/8) ≈ 0.3827

    let x0 = input[0];
    let x1 = input[1];
    let x2 = input[2];
    let x3 = input[3];

    // IDCT-III formula: out[k] = x[0] + 2 * sum_{n=1..N-1} x[n] * cos(pi*n*(2k+1)/(2N))
    // For N=4:
    output[0] = x0
        + 2.0
            * (x1 * (core::f32::consts::PI * 1.0 / 8.0).cos()
                + x2 * (core::f32::consts::PI * 2.0 / 8.0).cos()
                + x3 * (core::f32::consts::PI * 3.0 / 8.0).cos());
    output[1] = x0
        + 2.0
            * (x1 * (core::f32::consts::PI * 3.0 / 8.0).cos()
                + x2 * (core::f32::consts::PI * 6.0 / 8.0).cos()
                + x3 * (core::f32::consts::PI * 9.0 / 8.0).cos());
    output[2] = x0
        + 2.0
            * (x1 * (core::f32::consts::PI * 5.0 / 8.0).cos()
                + x2 * (core::f32::consts::PI * 10.0 / 8.0).cos()
                + x3 * (core::f32::consts::PI * 15.0 / 8.0).cos());
    output[3] = x0
        + 2.0
            * (x1 * (core::f32::consts::PI * 7.0 / 8.0).cos()
                + x2 * (core::f32::consts::PI * 14.0 / 8.0).cos()
                + x3 * (core::f32::consts::PI * 21.0 / 8.0).cos());

    // Suppress unused variable warning
    let _ = (c1, c3);
}

/// Extract DC values from 32x32 DCT coefficients.
/// Returns 16 DC values (for the 16 covered 8x8 blocks) in row-major 4x4 order.
///
/// The LLF region is 4x4 coefficients at positions `[r*32+c]` for r,c in 0..4
/// in the 32x32 layout (stride 32). We apply `DCTTotalResampleScale<32, 4>` to
/// each dimension, then a 4x4 IDCT to get the 16 DC values.
///
/// C++ uses `ReinterpretingIDCT<32, 32, 4, 4, 4, 4>` with the ROWS >= COLS branch
/// (since ROWS=COLS=4).
pub fn dc_from_dct_32x32(coeffs: &[f32; 1024]) -> [f32; 16] {
    // Step 1: Extract 4x4 LLF and apply resample scales
    let mut block = [0.0f32; 16];
    for iy in 0..4 {
        for ix in 0..4 {
            block[iy * 4 + ix] = coeffs[iy * 32 + ix]
                * DCT_RESAMPLE_SCALE_32_TO_4[iy]
                * DCT_RESAMPLE_SCALE_32_TO_4[ix];
        }
    }

    // Step 2: 4x4 IDCT via row-wise then column-wise 4-point IDCT
    // Row-wise
    let mut after_rows = [0.0f32; 16];
    for iy in 0..4 {
        let row_in: [f32; 4] = [
            block[iy * 4],
            block[iy * 4 + 1],
            block[iy * 4 + 2],
            block[iy * 4 + 3],
        ];
        let mut row_out = [0.0f32; 4];
        idct1d_4(&row_in, &mut row_out);
        for ix in 0..4 {
            after_rows[iy * 4 + ix] = row_out[ix];
        }
    }

    // Column-wise
    let mut result = [0.0f32; 16];
    for ix in 0..4 {
        let col_in: [f32; 4] = [
            after_rows[ix],
            after_rows[4 + ix],
            after_rows[8 + ix],
            after_rows[12 + ix],
        ];
        let mut col_out = [0.0f32; 4];
        idct1d_4(&col_in, &mut col_out);
        for iy in 0..4 {
            result[iy * 4 + ix] = col_out[iy];
        }
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dct1d_2() {
        let mut data = [1.0, 2.0];
        dct1d_2(&mut data);
        assert!((data[0] - 3.0).abs() < 1e-6);
        assert!((data[1] - (-1.0)).abs() < 1e-6);
    }

    #[test]
    fn test_dct1d_4() {
        // Constant input should give DC-only output
        let mut data = [1.0, 1.0, 1.0, 1.0];
        dct1d_4(&mut data);
        // DC should be 4.0 (sum), AC should be ~0
        assert!((data[0] - 4.0).abs() < 1e-5, "DC: {}", data[0]);
        for (i, val) in data.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-5, "AC[{}]: {}", i, val);
        }
    }

    #[test]
    fn test_dct1d_8() {
        // Constant input should give DC-only output
        let mut data = [1.0; 8];
        dct1d_8(&mut data);
        // DC should be 8.0 (sum), AC should be ~0
        assert!((data[0] - 8.0).abs() < 1e-5, "DC: {}", data[0]);
        for (i, val) in data.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-5, "AC[{}]: {}", i, val);
        }
    }

    #[test]
    fn test_dct_8x8_constant() {
        // Constant 8x8 block should have only DC
        let input = [0.5f32; 64];
        let mut output = [0.0f32; 64];
        dct_8x8(&input, &mut output);

        // DC = sum / 64 = 32 / 64 = 0.5, but with scaling it's sum * (1/8)^2 = 32/64 = 0.5
        // Actually for constant input, DCT gives DC = sum * normalization
        // With our 1/N scaling per dimension: DC = 8 * 0.5 / 8 * 8 / 8 = 0.5
        // This depends on the exact normalization. Let's just check AC is zero.
        for (i, val) in output.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-4, "AC[{}]: {} should be ~0", i, val);
        }
    }

    #[test]
    fn test_dct_8x8_energy_preservation() {
        // DCT should preserve energy (Parseval's theorem)
        let input: [f32; 64] = core::array::from_fn(|i| (i as f32) / 64.0);
        let mut output = [0.0f32; 64];
        dct_8x8(&input, &mut output);

        let _input_energy: f32 = input.iter().map(|x| x * x).sum();
        let output_energy: f32 = output.iter().map(|x| x * x).sum();

        // Energy may differ by normalization factor, but should be proportional
        assert!(output_energy > 0.0, "Output should have non-zero energy");
    }

    #[test]
    fn test_dc_from_dct_8x8() {
        let mut coeffs = [0.0f32; 64];
        coeffs[0] = 42.0;
        assert_eq!(dc_from_dct_8x8(&coeffs), 42.0);
    }

    #[test]
    fn test_dc_from_dct_16x8() {
        // Test with known values
        let mut coeffs = [0.0f32; 128];
        coeffs[0] = 1.0;
        let dc = dc_from_dct_16x8(&coeffs);
        // With only lf0=1.0 and lf1=0, we get [1, 1] from IDCT
        assert!((dc[0] - 1.0).abs() < 1e-5);
        assert!((dc[1] - 1.0).abs() < 1e-5);
    }

    #[test]
    fn test_dct_16x16_constant() {
        // Constant 16x16 block should have only DC, all AC ~0
        let input = [0.5f32; 256];
        let mut output = [0.0f32; 256];
        dct_16x16(&input, &mut output);

        // AC should be zero
        for (i, val) in output.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-4, "AC[{}]: {} should be ~0", i, val);
        }
    }

    #[test]
    fn test_dct_16x16_no_final_transpose() {
        // Verify the output layout: coefficients should NOT be transposed back.
        // For a block that's non-zero only along row 0, the DCT should produce
        // coefficients that vary along the frequency row direction (index / 16)
        // but are zero for frequency column > 0 (index % 16 > 0).
        let mut input = [0.0f32; 256];
        // Set row 0 to a specific pattern
        for (x, val) in input.iter_mut().enumerate().take(16) {
            *val = (x as f32 + 1.0) / 16.0;
        }
        let mut output = [0.0f32; 256];
        dct_16x16(&input, &mut output);

        // After DCT with no transpose: the horizontal transform is applied first,
        // then vertical. With only row 0 non-zero, the vertical transform produces
        // DC in all rows. So we should have non-zero values in column 0 (indices 0, 16, 32, ...)
        // but also in other positions due to the non-trivial row content.
        // Key check: output[1] should be non-zero (it's the (0,1) frequency),
        // NOT at output[16] which would be the case with a final transpose.
        assert!(
            output[1].abs() > 1e-6,
            "output[1] should be non-zero for non-trivial row 0"
        );
    }

    #[test]
    fn test_dc_from_dct_16x16_uniform() {
        // Uniform input: all 4 DC values should be equal
        let input = [1.0f32; 256];
        let mut output = [0.0f32; 256];
        dct_16x16(&input, &mut output);
        let dc = dc_from_dct_16x16(&output);

        // All 4 DC values should be approximately equal (uniform input)
        for i in 1..4 {
            assert!(
                (dc[i] - dc[0]).abs() < 1e-3,
                "dc[{}]={} should equal dc[0]={}",
                i,
                dc[i],
                dc[0]
            );
        }
    }

    #[test]
    fn test_dc_from_dct_16x16_dc_only() {
        // If only LLF[0] (DC) is set, all 4 outputs should be equal
        let mut coeffs = [0.0f32; 256];
        coeffs[0] = 4.0;
        let dc = dc_from_dct_16x16(&coeffs);
        // With b00=4, b01=b10=b11=0:
        // dc00 = dc01 = dc10 = dc11 = 4.0
        for (i, val) in dc.iter().enumerate() {
            assert!((*val - 4.0).abs() < 1e-5, "dc[{}]={} should be 4.0", i, val);
        }
    }

    // ─── DCT32 tests ──────────────────────────────────────────────────

    #[test]
    fn test_dct1d_32_constant() {
        // Constant input should give DC-only output
        let mut data = [1.0f32; 32];
        dct1d_32(&mut data);
        // DC should be 32.0 (sum), AC should be ~0
        assert!(
            (data[0] - 32.0).abs() < 1e-3,
            "DC: {} expected 32.0",
            data[0]
        );
        for (i, val) in data.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-3, "AC[{}]: {} should be ~0", i, val);
        }
    }

    #[test]
    fn test_dct_32x32_constant() {
        // Constant 32x32 block should have only DC, all AC ~0
        let input = [0.5f32; 1024];
        let mut output = [0.0f32; 1024];
        dct_32x32(&input, &mut output);

        // AC should be zero
        for (i, val) in output.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-3, "AC[{}]: {} should be ~0", i, val);
        }
    }

    #[test]
    fn test_dc_from_dct_32x32_uniform() {
        // Uniform input: all 16 DC values should be approximately equal
        let input = [1.0f32; 1024];
        let mut output = [0.0f32; 1024];
        dct_32x32(&input, &mut output);
        let dc = dc_from_dct_32x32(&output);

        // All 16 DC values should be approximately equal (uniform input)
        for i in 1..16 {
            assert!(
                (dc[i] - dc[0]).abs() < 1e-2,
                "dc[{}]={} should equal dc[0]={}",
                i,
                dc[i],
                dc[0]
            );
        }
    }

    #[test]
    fn test_dc_from_dct_32x32_dc_only() {
        // If only LLF[0] (DC) is set, all 16 outputs should be equal
        let mut coeffs = [0.0f32; 1024];
        coeffs[0] = 16.0;
        let dc = dc_from_dct_32x32(&coeffs);
        // All should be equal since only DC is set
        for i in 1..16 {
            assert!(
                (dc[i] - dc[0]).abs() < 1e-3,
                "dc[{}]={} should equal dc[0]={}",
                i,
                dc[i],
                dc[0]
            );
        }
    }

    #[test]
    fn test_dct_32x32_no_final_transpose() {
        // Verify no final transpose: input with only row 0 non-zero
        let mut input = [0.0f32; 1024];
        for (x, val) in input.iter_mut().enumerate().take(32) {
            *val = (x as f32 + 1.0) / 32.0;
        }
        let mut output = [0.0f32; 1024];
        dct_32x32(&input, &mut output);

        // output[1] should be non-zero (horizontal frequency)
        assert!(
            output[1].abs() > 1e-6,
            "output[1] should be non-zero for non-trivial row 0"
        );
    }
}
