// Copyright (c) the JPEG XL Project Authors. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//! Forward DCT transforms ported from libjxl-tiny and libjxl.
//!
//! Implements the "Lowest Complexity Self Recursive Radix-2 DCT II/III
//! Algorithms" by Siriani M. Perera and Jianhua Liu.
//!
//! Also includes IDENTITY and DCT2X2 transforms from full libjxl
//! (enc_transforms-inl.h).

// Ported float constants from C++ - exact values are intentional for parity.
#![allow(clippy::excessive_precision)]
#![allow(clippy::approx_constant)]
#![allow(dead_code)]

// =============================================================================
// Constants from libjxl-tiny dct_scales.h
// IMPORTANT: These values are copied exactly from the C++ source.
// =============================================================================

/// sqrt(2) constant used in DCT
pub const SQRT2: f32 = 1.41421356237;

/// Multipliers for DCT computation.
/// Generated by: `1.0 / (2 * cos((i + 0.5) * pi / N))` for i in 0..N/2
// Copied directly from libjxl-tiny dct_scales.h
pub const WC_MULTIPLIERS_4: [f32; 2] = [0.541196100146197, 1.3065629648763764];

// Copied directly from libjxl-tiny dct_scales.h
pub const WC_MULTIPLIERS_8: [f32; 4] = [
    0.5097955791041592,
    0.6013448869350453,
    0.8999762231364156,
    2.5629154477415055,
];

// Copied directly from libjxl-tiny dct_scales.h
pub const WC_MULTIPLIERS_16: [f32; 8] = [
    0.5024192861881557,
    0.5224986149396889,
    0.5669440348163577,
    0.6468217833599901,
    0.7881546234512502,
    1.060677685990347,
    1.7224470982383342,
    5.101148618689155,
];

/// Resample scales for DC extraction from larger DCTs.
// Copied directly from libjxl-tiny dct_scales.h
pub const DCT_RESAMPLE_SCALE_16_TO_2: [f32; 2] = [1.000000000000000000, 0.901764195028874394];

pub const DCT_RESAMPLE_SCALE_2_TO_16: [f32; 2] = [1.000000000000000000, 1.108937353592731823];

// =============================================================================
// DCT Algorithm Implementation
// =============================================================================

/// In-place 1D DCT for N=2
#[inline]
fn dct1d_2(mem: &mut [f32]) {
    let in1 = mem[0];
    let in2 = mem[1];
    mem[0] = in1 + in2;
    mem[1] = in1 - in2;
}

/// In-place 1D DCT for N=4
fn dct1d_4(mem: &mut [f32]) {
    // AddReverse: tmp[i] = mem[i] + mem[N-1-i] for first half
    // SubReverse: tmp[N/2+i] = mem[i] - mem[N-1-i] for second half
    let mut tmp = [0.0f32; 4];
    tmp[0] = mem[0] + mem[3];
    tmp[1] = mem[1] + mem[2];
    tmp[2] = mem[0] - mem[3];
    tmp[3] = mem[1] - mem[2];

    // DCT on first half
    dct1d_2(&mut tmp[0..2]);

    // Multiply second half by WcMultipliers
    tmp[2] *= WC_MULTIPLIERS_4[0];
    tmp[3] *= WC_MULTIPLIERS_4[1];

    // DCT on second half
    dct1d_2(&mut tmp[2..4]);

    // B transform on second half
    // B: tmp[0] = sqrt2 * tmp[0] + tmp[1], then tmp[i] = tmp[i] + tmp[i+1] for rest
    tmp[2] = SQRT2 * tmp[2] + tmp[3];
    // (no more elements for N/2=2)

    // InverseEvenOdd: interleave even and odd
    mem[0] = tmp[0];
    mem[2] = tmp[1];
    mem[1] = tmp[2];
    mem[3] = tmp[3];
}

/// In-place 1D DCT for N=8
fn dct1d_8(mem: &mut [f32]) {
    let mut tmp = [0.0f32; 8];

    // AddReverse for first half
    for i in 0..4 {
        tmp[i] = mem[i] + mem[7 - i];
    }
    // SubReverse for second half
    for i in 0..4 {
        tmp[4 + i] = mem[i] - mem[7 - i];
    }

    // DCT on first half
    dct1d_4(&mut tmp[0..4]);

    // Multiply second half by WcMultipliers
    for i in 0..4 {
        tmp[4 + i] *= WC_MULTIPLIERS_8[i];
    }

    // DCT on second half
    dct1d_4(&mut tmp[4..8]);

    // B transform on second half
    tmp[4] = SQRT2 * tmp[4] + tmp[5];
    tmp[5] += tmp[6];
    tmp[6] += tmp[7];

    // InverseEvenOdd: interleave
    for i in 0..4 {
        mem[2 * i] = tmp[i];
        mem[2 * i + 1] = tmp[4 + i];
    }
}

/// In-place 1D DCT for N=16
fn dct1d_16(mem: &mut [f32]) {
    let mut tmp = [0.0f32; 16];

    // AddReverse for first half
    for i in 0..8 {
        tmp[i] = mem[i] + mem[15 - i];
    }
    // SubReverse for second half
    for i in 0..8 {
        tmp[8 + i] = mem[i] - mem[15 - i];
    }

    // DCT on first half
    dct1d_8(&mut tmp[0..8]);

    // Multiply second half by WcMultipliers
    for i in 0..8 {
        tmp[8 + i] *= WC_MULTIPLIERS_16[i];
    }

    // DCT on second half
    dct1d_8(&mut tmp[8..16]);

    // B transform on second half
    tmp[8] = SQRT2 * tmp[8] + tmp[9];
    for i in 1..7 {
        tmp[8 + i] += tmp[8 + i + 1];
    }

    // InverseEvenOdd: interleave
    for i in 0..8 {
        mem[2 * i] = tmp[i];
        mem[2 * i + 1] = tmp[8 + i];
    }
}

/// Transpose an NxM block in-place (actually copies to output).
fn transpose<const N: usize, const M: usize>(input: &[f32], output: &mut [f32]) {
    for row in 0..N {
        for col in 0..M {
            output[col * N + row] = input[row * M + col];
        }
    }
}

/// Compute scaled 8x8 DCT.
///
/// Input: 8x8 block in row-major order
/// Output: 8x8 DCT coefficients in **transposed** layout
///
/// IMPORTANT: libjxl-tiny's ComputeScaledDCT does NOT transpose back for square blocks.
/// The decoder expects coefficients in this transposed layout. For 8x8 blocks,
/// output[cx * 8 + cy] contains the coefficient for frequency (cy, cx) where
/// cy is the vertical frequency and cx is the horizontal frequency.
pub fn dct_8x8(input: &[f32; 64], output: &mut [f32; 64]) {
    let mut tmp = [0.0f32; 64];

    // Transform rows
    for row in 0..8 {
        let row_start = row * 8;
        tmp[row_start..row_start + 8].copy_from_slice(&input[row_start..row_start + 8]);
        dct1d_8(&mut tmp[row_start..row_start + 8]);
        // Scale by 1/N
        for i in 0..8 {
            tmp[row_start + i] *= 1.0 / 8.0;
        }
    }

    // Transpose
    let mut transposed = [0.0f32; 64];
    transpose::<8, 8>(&tmp, &mut transposed);

    // Transform columns (now rows after transpose)
    for row in 0..8 {
        let row_start = row * 8;
        dct1d_8(&mut transposed[row_start..row_start + 8]);
        // Scale by 1/N
        for i in 0..8 {
            transposed[row_start + i] *= 1.0 / 8.0;
        }
    }

    // DO NOT transpose back! libjxl-tiny expects transposed output for square blocks.
    // This matches ComputeScaledDCT in libjxl-tiny/encoder/enc_transforms-inl.h
    output.copy_from_slice(&transposed);
}

/// Compute base 4x8 DCT (4 rows, 8 columns).
///
/// This is the primitive transform for a single 4x8 sub-block.
/// Input: 4x8 = 32 floats in row-major order
/// Output: 32 DCT coefficients
///
/// Based on libjxl's ComputeScaledDCT<4, 8>. Since ROWS < COLS,
/// the transform includes a final transpose.
pub fn dct_4x8(input: &[f32; 32], output: &mut [f32; 32]) {
    let mut tmp = [0.0f32; 32];

    // Transform rows (8 columns each) with 8-point DCT
    for row in 0..4 {
        let row_start = row * 8;
        tmp[row_start..row_start + 8].copy_from_slice(&input[row_start..row_start + 8]);
        dct1d_8(&mut tmp[row_start..row_start + 8]);
        for i in 0..8 {
            tmp[row_start + i] *= 1.0 / 8.0;
        }
    }

    // Transpose 4x8 -> 8x4
    let mut transposed = [0.0f32; 32];
    for row in 0..4 {
        for col in 0..8 {
            transposed[col * 4 + row] = tmp[row * 8 + col];
        }
    }

    // Transform columns (now 4 elements each) with 4-point DCT
    for row in 0..8 {
        let row_start = row * 4;
        dct1d_4(&mut transposed[row_start..row_start + 4]);
        for i in 0..4 {
            transposed[row_start + i] *= 1.0 / 4.0;
        }
    }

    // Final transpose 8x4 -> 4x8 (ROWS < COLS branch in libjxl)
    for row in 0..8 {
        for col in 0..4 {
            output[col * 8 + row] = transposed[row * 4 + col];
        }
    }
}

/// Compute base 8x4 DCT (8 rows, 4 columns).
///
/// This is the primitive transform for a single 8x4 sub-block.
/// Input: 8x4 = 32 floats in row-major order
/// Output: 32 DCT coefficients
///
/// Based on libjxl's ComputeScaledDCT<8, 4>. Since ROWS >= COLS,
/// there is NO final transpose.
pub fn dct_8x4(input: &[f32; 32], output: &mut [f32; 32]) {
    let mut tmp = [0.0f32; 32];

    // Transform rows (4 columns each) with 4-point DCT
    for row in 0..8 {
        let row_start = row * 4;
        tmp[row_start..row_start + 4].copy_from_slice(&input[row_start..row_start + 4]);
        dct1d_4(&mut tmp[row_start..row_start + 4]);
        for i in 0..4 {
            tmp[row_start + i] *= 1.0 / 4.0;
        }
    }

    // Transpose 8x4 -> 4x8
    let mut transposed = [0.0f32; 32];
    for row in 0..8 {
        for col in 0..4 {
            transposed[col * 8 + row] = tmp[row * 4 + col];
        }
    }

    // Transform columns (now 8 elements each) with 8-point DCT
    for row in 0..4 {
        let row_start = row * 8;
        dct1d_8(&mut transposed[row_start..row_start + 8]);
        for i in 0..8 {
            transposed[row_start + i] *= 1.0 / 8.0;
        }
    }

    // NO final transpose for ROWS >= COLS (matches dct_8x8 behavior)
    output.copy_from_slice(&transposed);
}

/// Compute full DCT4X8 transform for 8x8 pixel block.
///
/// This covers an 8x8 pixel region using TWO vertically-stacked 4x8 sub-blocks.
/// The DC values of the two sub-blocks are combined with a 2-point transform.
///
/// Input: 8x8 = 64 floats in row-major order (stride 8)
/// Output: 64 DCT coefficients in interleaved layout
///
/// Matches libjxl's Type::DCT4X8 case in enc_transforms-inl.h
pub fn dct_4x8_full(input: &[f32; 64], output: &mut [f32; 64]) {
    // Process two 4x8 sub-blocks (top and bottom halves)
    for y in 0..2 {
        // Extract 4x8 sub-block
        let mut block = [0.0f32; 32];
        for iy in 0..4 {
            for ix in 0..8 {
                block[iy * 8 + ix] = input[(y * 4 + iy) * 8 + ix];
            }
        }

        // Apply base 4x8 DCT
        let mut coeffs = [0.0f32; 32];
        dct_4x8(&block, &mut coeffs);

        // Interleave into output: coefficients[(y + iy * 2) * 8 + ix]
        for iy in 0..4 {
            for ix in 0..8 {
                output[(y + iy * 2) * 8 + ix] = coeffs[iy * 8 + ix];
            }
        }
    }

    // Combine DC values of the two sub-blocks with 2-point transform
    let block0_dc = output[0];
    let block1_dc = output[8];
    output[0] = (block0_dc + block1_dc) * 0.5;
    output[8] = (block0_dc - block1_dc) * 0.5;
}

/// Compute full DCT8X4 transform for 8x8 pixel block.
///
/// This covers an 8x8 pixel region using TWO horizontally-adjacent 8x4 sub-blocks.
/// The DC values of the two sub-blocks are combined with a 2-point transform.
///
/// Input: 8x8 = 64 floats in row-major order (stride 8)
/// Output: 64 DCT coefficients in interleaved layout
///
/// Matches libjxl's Type::DCT8X4 case in enc_transforms-inl.h
pub fn dct_8x4_full(input: &[f32; 64], output: &mut [f32; 64]) {
    // Process two 8x4 sub-blocks (left and right halves)
    for x in 0..2 {
        // Extract 8x4 sub-block
        let mut block = [0.0f32; 32];
        for iy in 0..8 {
            for ix in 0..4 {
                block[iy * 4 + ix] = input[iy * 8 + (x * 4 + ix)];
            }
        }

        // Apply base 8x4 DCT
        let mut coeffs = [0.0f32; 32];
        dct_8x4(&block, &mut coeffs);

        // Interleave into output: coefficients[(x + iy * 2) * 8 + ix]
        // Note: the 8x4 output is in 4x8 layout (stride 8) after the transform
        for iy in 0..4 {
            for ix in 0..8 {
                output[(x + iy * 2) * 8 + ix] = coeffs[iy * 8 + ix];
            }
        }
    }

    // Combine DC values of the two sub-blocks with 2-point transform
    let block0_dc = output[0];
    let block1_dc = output[8];
    output[0] = (block0_dc + block1_dc) * 0.5;
    output[8] = (block0_dc - block1_dc) * 0.5;
}

/// Extract DC value from DCT4X8 full transform coefficients.
///
/// For DCT4X8 (and DCT8X4), the 8x8 block is covered by a single 1x1 DC region.
/// The DC combining step already produced the DC at position [0].
#[inline]
pub fn dc_from_dct_4x8_full(coeffs: &[f32; 64]) -> f32 {
    coeffs[0]
}

/// Extract DC value from DCT8X4 full transform coefficients.
///
/// Same as DCT4X8 - single DC at position [0].
#[inline]
pub fn dc_from_dct_8x4_full(coeffs: &[f32; 64]) -> f32 {
    coeffs[0]
}

/// Compute base 4x4 DCT.
///
/// Input: 4x4 = 16 floats in row-major order (stride 4)
/// Output: 16 DCT coefficients
///
/// Based on libjxl's ComputeScaledDCT<4, 4>. Since ROWS == COLS (square),
/// there is NO final transpose.
pub fn dct_4x4(input: &[f32; 16], output: &mut [f32; 16]) {
    let mut tmp = [0.0f32; 16];

    // Transform rows with 4-point DCT
    for row in 0..4 {
        let row_start = row * 4;
        tmp[row_start..row_start + 4].copy_from_slice(&input[row_start..row_start + 4]);
        dct1d_4(&mut tmp[row_start..row_start + 4]);
        for i in 0..4 {
            tmp[row_start + i] *= 1.0 / 4.0;
        }
    }

    // Transpose 4x4
    let mut transposed = [0.0f32; 16];
    for row in 0..4 {
        for col in 0..4 {
            transposed[col * 4 + row] = tmp[row * 4 + col];
        }
    }

    // Transform columns (now rows after transpose) with 4-point DCT
    for row in 0..4 {
        let row_start = row * 4;
        dct1d_4(&mut transposed[row_start..row_start + 4]);
        for i in 0..4 {
            transposed[row_start + i] *= 1.0 / 4.0;
        }
    }

    // No final transpose for square blocks (ROWS >= COLS in libjxl)
    // Output is in transposed layout
    output.copy_from_slice(&transposed);
}

/// Compute full DCT4X4 transform for 8x8 pixel block.
///
/// This covers an 8x8 pixel region using FOUR 4x4 sub-blocks arranged in a 2x2 grid.
/// The DC values of the four sub-blocks are combined with a 2x2 DCT.
///
/// Input: 8x8 = 64 floats in row-major order (stride 8)
/// Output: 64 DCT coefficients in interleaved layout
///
/// Matches libjxl's Type::DCT4X4 case in enc_transforms-inl.h
pub fn dct_4x4_full(input: &[f32; 64], output: &mut [f32; 64]) {
    // Process four 4x4 sub-blocks in 2x2 grid
    for y in 0..2 {
        for x in 0..2 {
            // Extract 4x4 sub-block
            let mut block = [0.0f32; 16];
            for iy in 0..4 {
                for ix in 0..4 {
                    block[iy * 4 + ix] = input[(y * 4 + iy) * 8 + (x * 4 + ix)];
                }
            }

            // Apply base 4x4 DCT
            let mut coeffs = [0.0f32; 16];
            dct_4x4(&block, &mut coeffs);

            // Interleave into output: coefficients[(y + iy * 2) * 8 + x + ix * 2]
            for iy in 0..4 {
                for ix in 0..4 {
                    output[(y + iy * 2) * 8 + x + ix * 2] = coeffs[iy * 4 + ix];
                }
            }
        }
    }

    // Combine DC values of the four sub-blocks with 2x2 DCT
    // Sub-block DCs are at positions: (0,0)->0, (0,1)->1, (1,0)->8, (1,1)->9
    let block00 = output[0];
    let block01 = output[1];
    let block10 = output[8];
    let block11 = output[9];

    // 2x2 DCT: same as libjxl's DC combining
    output[0] = (block00 + block01 + block10 + block11) * 0.25;
    output[1] = (block00 + block01 - block10 - block11) * 0.25;
    output[8] = (block00 - block01 + block10 - block11) * 0.25;
    output[9] = (block00 - block01 - block10 + block11) * 0.25;
}

/// Extract DC value from DCT4X4 full transform coefficients.
///
/// For DCT4X4, the 8x8 block has a 2x2 LLF region at positions [0,1,8,9].
/// The DC (average) is at position [0].
#[inline]
pub fn dc_from_dct_4x4_full(coeffs: &[f32; 64]) -> f32 {
    coeffs[0]
}

/// Compute scaled 16x8 DCT (16 rows, 8 columns).
///
/// Input: 16x8 block in row-major order (128 floats)
/// Output: 16x8 DCT coefficients
pub fn dct_16x8(input: &[f32; 128], output: &mut [f32; 128]) {
    let mut tmp = [0.0f32; 128];

    // Transform rows (8 columns each)
    for row in 0..16 {
        let row_start = row * 8;
        tmp[row_start..row_start + 8].copy_from_slice(&input[row_start..row_start + 8]);
        dct1d_8(&mut tmp[row_start..row_start + 8]);
        for i in 0..8 {
            tmp[row_start + i] *= 1.0 / 8.0;
        }
    }

    // Transpose 16x8 -> 8x16
    let mut transposed = [0.0f32; 128];
    for row in 0..16 {
        for col in 0..8 {
            transposed[col * 16 + row] = tmp[row * 8 + col];
        }
    }

    // Transform columns (now 16 elements each)
    for row in 0..8 {
        let row_start = row * 16;
        dct1d_16(&mut transposed[row_start..row_start + 16]);
        for i in 0..16 {
            transposed[row_start + i] *= 1.0 / 16.0;
        }
    }

    // No final transpose — C++ ComputeScaledDCT<16,8> (ROWS >= COLS branch)
    // does not include a final transpose, matching DCT8x8 behavior.
    // Output is in 8x16 layout: output[fx * 16 + fy] for frequency (fy, fx).
    output.copy_from_slice(&transposed);
}

/// Compute scaled 8x16 DCT (8 rows, 16 columns).
///
/// Input: 8x16 block in row-major order (128 floats)
/// Output: 8x16 DCT coefficients
pub fn dct_8x16(input: &[f32; 128], output: &mut [f32; 128]) {
    let mut tmp = [0.0f32; 128];

    // Transform rows (16 columns each)
    for row in 0..8 {
        let row_start = row * 16;
        tmp[row_start..row_start + 16].copy_from_slice(&input[row_start..row_start + 16]);
        dct1d_16(&mut tmp[row_start..row_start + 16]);
        for i in 0..16 {
            tmp[row_start + i] *= 1.0 / 16.0;
        }
    }

    // Transpose 8x16 -> 16x8
    let mut transposed = [0.0f32; 128];
    for row in 0..8 {
        for col in 0..16 {
            transposed[col * 8 + row] = tmp[row * 16 + col];
        }
    }

    // Transform columns (now 8 elements each)
    for row in 0..16 {
        let row_start = row * 8;
        dct1d_8(&mut transposed[row_start..row_start + 8]);
        for i in 0..8 {
            transposed[row_start + i] *= 1.0 / 8.0;
        }
    }

    // Transpose 16x8 -> 8x16
    for row in 0..16 {
        for col in 0..8 {
            output[col * 16 + row] = transposed[row * 8 + col];
        }
    }
}

/// Compute scaled 16x16 DCT (16 rows, 16 columns).
///
/// Input: 16x16 block in row-major order (256 floats)
/// Output: 16x16 DCT coefficients
///
/// Like `dct_8x8()`, there is NO final transpose for square blocks.
/// C++ `ComputeScaledDCT<16,16>` takes the ROWS >= COLS branch (no final transpose).
pub fn dct_16x16(input: &[f32; 256], output: &mut [f32; 256]) {
    let mut tmp = [0.0f32; 256];

    // Transform rows (16 columns each)
    for row in 0..16 {
        let row_start = row * 16;
        tmp[row_start..row_start + 16].copy_from_slice(&input[row_start..row_start + 16]);
        dct1d_16(&mut tmp[row_start..row_start + 16]);
        // Scale by 1/N
        for i in 0..16 {
            tmp[row_start + i] *= 1.0 / 16.0;
        }
    }

    // Transpose 16x16
    let mut transposed = [0.0f32; 256];
    transpose::<16, 16>(&tmp, &mut transposed);

    // Transform columns (now rows after transpose)
    for row in 0..16 {
        let row_start = row * 16;
        dct1d_16(&mut transposed[row_start..row_start + 16]);
        // Scale by 1/N
        for i in 0..16 {
            transposed[row_start + i] *= 1.0 / 16.0;
        }
    }

    // DO NOT transpose back! Same as DCT8x8 - square blocks stay transposed.
    output.copy_from_slice(&transposed);
}

/// Extract DC values from 16x16 DCT coefficients.
/// Returns 4 DC values in spatial order: `[top-left, top-right, bottom-left, bottom-right]`.
///
/// The caller stores `dcs[iy * 2 + ix]` at position `(by + iy, bx + ix)`, so:
///   dcs[0] → (by, bx), dcs[1] → (by, bx+1), dcs[2] → (by+1, bx), dcs[3] → (by+1, bx+1).
///
/// The LLF region is 2x2 coefficients at positions [0, 1, 16, 17] in the 16x16 layout
/// (stride 16). We apply `DCTTotalResampleScale<16, 2>` to each dimension, then a
/// 2x2 IDCT to get the 4 DC values.
///
/// C++ uses `ReinterpretingIDCT<16, 16, 2, 2, 2, 2>` → `ComputeScaledIDCT<2, 2>`.
/// The IDCT steps (ROWS >= COLS branch): IDCT rows → transpose → IDCT rows.
/// The transpose between steps swaps off-diagonal elements.
pub fn dc_from_dct_16x16(coeffs: &[f32; 256]) -> [f32; 4] {
    let s0 = DCT_RESAMPLE_SCALE_16_TO_2[0]; // 1.0
    let s1 = DCT_RESAMPLE_SCALE_16_TO_2[1]; // 0.9018...

    // Read LLF 2x2 from positions [0, 1, 16, 17] and apply resample scales.
    // C++ ROWS >= COLS: block[y * ROWS + x] = input[y * stride + x] * scale_col[y] * scale_row[x]
    let b00 = coeffs[0] * s0 * s0;
    let b01 = coeffs[1] * s0 * s1;
    let b10 = coeffs[16] * s1 * s0;
    let b11 = coeffs[17] * s1 * s1;

    // 2x2 IDCT (ComputeScaledIDCT<2,2>, ROWS >= COLS):
    // Step 1 — IDCT rows (length 2): [a, b] → [a+b, a-b]
    //   Row 0: [b00+b01, b00-b01]
    //   Row 1: [b10+b11, b10-b11]
    // Step 2 — Transpose 2×2:
    //   [b00+b01, b10+b11]
    //   [b00-b01, b10-b11]
    // Step 3 — IDCT rows (length 2):
    //   out[0,0] = (b00+b01) + (b10+b11)
    //   out[0,1] = (b00+b01) - (b10+b11)
    //   out[1,0] = (b00-b01) + (b10-b11)
    //   out[1,1] = (b00-b01) - (b10-b11)
    let out00 = (b00 + b01) + (b10 + b11); // top-left
    let out01 = (b00 + b01) - (b10 + b11); // top-right
    let out10 = (b00 - b01) + (b10 - b11); // bottom-left
    let out11 = (b00 - b01) - (b10 - b11); // bottom-right

    [out00, out01, out10, out11]
}

// ============================================================================
// Inverse DCT (IDCT) implementations for pixel-domain loss calculation
// ============================================================================
//
// NOTE: These IDCT functions use a simple reference implementation. The
// roundtrip (DCT → IDCT) is not perfectly accurate for all inputs due to
// scaling differences with the optimized forward DCT. For the pixel-domain
// loss in EstimateEntropy, relative magnitudes matter more than exact values.
// If exact roundtrip is needed, the scaling factor should be calibrated
// empirically or a matched IDCT algorithm should be implemented.

/// Fast 1D IDCT for N=2 (exactly reverses dct1d_2).
/// Forward: [a, b] → [a+b, a-b]
/// Inverse: [x, y] → [(x+y)/2, (x-y)/2]
#[inline]
fn idct1d_2(mem: &mut [f32]) {
    let x = mem[0];
    let y = mem[1];
    mem[0] = (x + y) * 0.5;
    mem[1] = (x - y) * 0.5;
}

/// Fast 1D IDCT for N=4 (exactly reverses dct1d_4).
fn idct1d_4(mem: &mut [f32]) {
    // Reverse step 7 (interleave): tmp = [mem[0], mem[2], mem[1], mem[3]]
    let mut tmp = [mem[0], mem[2], mem[1], mem[3]];

    // Reverse step 6 (B transform): original was tmp[2] = sqrt2*tmp[2] + tmp[3]
    tmp[2] = (tmp[2] - tmp[3]) / SQRT2;

    // Reverse step 5: idct on second half
    idct1d_2(&mut tmp[2..4]);

    // Reverse step 4: divide by WcMultipliers
    tmp[2] /= WC_MULTIPLIERS_4[0];
    tmp[3] /= WC_MULTIPLIERS_4[1];

    // Reverse step 3: idct on first half
    idct1d_2(&mut tmp[0..2]);

    // Reverse steps 1-2: combine even/odd
    // Forward: e0 = a+d, e1 = b+c, o0 = a-d, o1 = b-c
    // Inverse: a = (e0+o0)/2, d = (e0-o0)/2, b = (e1+o1)/2, c = (e1-o1)/2
    let e0 = tmp[0];
    let e1 = tmp[1];
    let o0 = tmp[2];
    let o1 = tmp[3];
    mem[0] = (e0 + o0) * 0.5;
    mem[3] = (e0 - o0) * 0.5;
    mem[1] = (e1 + o1) * 0.5;
    mem[2] = (e1 - o1) * 0.5;
}

/// Core 1D IDCT for N=8 without the N scaling factor.
///
/// This reverses the dct1d_8 butterfly operations only, without compensating
/// for the 1/N scaling applied by the 2D wrapper (dct_8x8). Used internally
/// by idct1d_16 which applies its own scaling.
fn idct1d_8_core(mem: &mut [f32]) {
    // Reverse step 7 (interleave)
    let mut tmp = [0.0f32; 8];
    for i in 0..4 {
        tmp[i] = mem[2 * i];
        tmp[4 + i] = mem[2 * i + 1];
    }

    // Reverse step 6 (B transform)
    tmp[6] -= tmp[7];
    tmp[5] -= tmp[6];
    tmp[4] = (tmp[4] - tmp[5]) / SQRT2;

    // Reverse step 5: idct on second half
    idct1d_4(&mut tmp[4..8]);

    // Reverse step 4: divide by WcMultipliers
    for i in 0..4 {
        tmp[4 + i] /= WC_MULTIPLIERS_8[i];
    }

    // Reverse step 3: idct on first half
    idct1d_4(&mut tmp[0..4]);

    // Reverse steps 1-2: combine even/odd
    for i in 0..4 {
        mem[i] = (tmp[i] + tmp[4 + i]) * 0.5;
        mem[7 - i] = (tmp[i] - tmp[4 + i]) * 0.5;
    }
}

/// Fast 1D IDCT for N=8 (exactly reverses dct1d_8).
///
/// Includes the *= 8 scaling to compensate for the 1/8 applied by dct_8x8.
fn idct1d_8(mem: &mut [f32]) {
    // Scale by N to compensate for 1/N in forward transform
    for x in mem.iter_mut().take(8) {
        *x *= 8.0;
    }
    idct1d_8_core(mem);
}

/// Fast 1D IDCT for N=16 (exactly reverses dct1d_16).
///
/// Includes *= 16 scaling to compensate for the 1/16 applied by dct_16x16.
/// Uses idct1d_8_core (without 8x scaling) for the recursive sub-transforms
/// since the scaling is handled at this level.
fn idct1d_16(mem: &mut [f32]) {
    // Scale by N to compensate for 1/N in forward transform
    for x in mem.iter_mut().take(16) {
        *x *= 16.0;
    }

    // Reverse step 7 (interleave): deinterleave
    let mut tmp = [0.0f32; 16];
    for i in 0..8 {
        tmp[i] = mem[2 * i];
        tmp[8 + i] = mem[2 * i + 1];
    }

    // Reverse step 6 (B transform):
    // Forward: tmp[8] = sqrt2*tmp[8] + tmp[9]; tmp[8+i] += tmp[8+i+1] for i in 1..7
    // Reverse: tmp[8+i] -= tmp[8+i+1] for i in (1..7).rev(); tmp[8] = (tmp[8] - tmp[9]) / sqrt2
    for i in (1..7).rev() {
        tmp[8 + i] -= tmp[8 + i + 1];
    }
    tmp[8] = (tmp[8] - tmp[9]) / SQRT2;

    // Reverse step 5: idct on second half (use core without 8x scaling)
    idct1d_8_core(&mut tmp[8..16]);

    // Reverse step 4: divide by WcMultipliers
    for i in 0..8 {
        tmp[8 + i] /= WC_MULTIPLIERS_16[i];
    }

    // Reverse step 3: idct on first half (use core without 8x scaling)
    idct1d_8_core(&mut tmp[0..8]);

    // Reverse steps 1-2: combine AddReverse/SubReverse
    // Forward: even[i] = mem[i] + mem[15-i], odd[i] = mem[i] - mem[15-i]
    // Inverse: mem[i] = (even[i] + odd[i])/2, mem[15-i] = (even[i] - odd[i])/2
    for i in 0..8 {
        mem[i] = (tmp[i] + tmp[8 + i]) * 0.5;
        mem[15 - i] = (tmp[i] - tmp[8 + i]) * 0.5;
    }
}

/// Reference 8-point 1D IDCT (formula-based, for use in larger IDCTs).
/// Input and output are separate arrays.
#[allow(clippy::needless_range_loop)]
fn idct1d_8_ref(input: &[f32], output: &mut [f32]) {
    let n = 8usize;
    let pi = core::f32::consts::PI;

    for k in 0..n {
        let mut sum = 0.5 * input[0];
        for j in 1..n {
            let angle = pi * (j as f32) * ((2 * k + 1) as f32) / (2.0 * n as f32);
            sum += input[j] * angle.cos();
        }
        output[k] = sum;
    }
}

/// Compute 8x8 inverse DCT (exactly reverses dct_8x8).
///
/// This uses the fast matched IDCT that exactly reverses our forward DCT algorithm.
/// Roundtrip error is essentially zero (floating point precision only).
pub fn idct_8x8(input: &[f32; 64], output: &mut [f32; 64]) {
    let mut tmp = [0.0f32; 64];

    // Copy input to tmp and apply IDCT to each row
    for row in 0..8 {
        let row_start = row * 8;
        tmp[row_start..row_start + 8].copy_from_slice(&input[row_start..row_start + 8]);
        idct1d_8(&mut tmp[row_start..row_start + 8]);
    }

    // Transpose
    let mut transposed = [0.0f32; 64];
    transpose::<8, 8>(&tmp, &mut transposed);

    // Apply IDCT to each row of transposed
    for row in 0..8 {
        let row_start = row * 8;
        output[row_start..row_start + 8].copy_from_slice(&transposed[row_start..row_start + 8]);
        idct1d_8(&mut output[row_start..row_start + 8]);
    }
}

/// Compute 16x16 inverse DCT (exactly reverses dct_16x16).
pub fn idct_16x16(input: &[f32; 256], output: &mut [f32; 256]) {
    let mut tmp = [0.0f32; 256];

    // Copy input and apply IDCT to each row
    for row in 0..16 {
        let row_start = row * 16;
        tmp[row_start..row_start + 16].copy_from_slice(&input[row_start..row_start + 16]);
        idct1d_16(&mut tmp[row_start..row_start + 16]);
    }

    // Transpose
    let mut transposed = [0.0f32; 256];
    transpose::<16, 16>(&tmp, &mut transposed);

    // Apply IDCT to each row (now columns)
    for row in 0..16 {
        let row_start = row * 16;
        output[row_start..row_start + 16].copy_from_slice(&transposed[row_start..row_start + 16]);
        idct1d_16(&mut output[row_start..row_start + 16]);
    }
}

/// Compute 16x8 inverse DCT (16 rows x 8 cols, exactly reverses dct_16x8).
pub fn idct_16x8(input: &[f32; 128], output: &mut [f32; 128]) {
    let mut tmp = [0.0f32; 128];

    // Apply 8-point IDCT to each row
    for row in 0..16 {
        let row_start = row * 8;
        tmp[row_start..row_start + 8].copy_from_slice(&input[row_start..row_start + 8]);
        idct1d_8(&mut tmp[row_start..row_start + 8]);
    }

    // Apply 16-point IDCT to each column (in-place via temporary column buffer)
    for col in 0..8 {
        let mut col_buf = [0.0f32; 16];
        for row in 0..16 {
            col_buf[row] = tmp[row * 8 + col];
        }
        idct1d_16(&mut col_buf);
        for row in 0..16 {
            output[row * 8 + col] = col_buf[row];
        }
    }
}

/// Compute 8x16 inverse DCT (8 rows x 16 cols, exactly reverses dct_8x16).
pub fn idct_8x16(input: &[f32; 128], output: &mut [f32; 128]) {
    let mut tmp = [0.0f32; 128];

    // Apply 16-point IDCT to each row
    for row in 0..8 {
        let row_start = row * 16;
        tmp[row_start..row_start + 16].copy_from_slice(&input[row_start..row_start + 16]);
        idct1d_16(&mut tmp[row_start..row_start + 16]);
    }

    // Apply 8-point IDCT to each column (in-place via temporary column buffer)
    for col in 0..16 {
        let mut col_buf = [0.0f32; 8];
        for row in 0..8 {
            col_buf[row] = tmp[row * 16 + col];
        }
        idct1d_8(&mut col_buf);
        for row in 0..8 {
            output[row * 16 + col] = col_buf[row];
        }
    }
}

/// Compute 4x4 inverse DCT (exactly reverses dct_4x4).
/// Input layout: 4 rows x 4 cols, stride 4.
pub fn idct_4x4(input: &[f32; 16], output: &mut [f32; 16]) {
    let mut tmp = [0.0f32; 16];

    // Apply 4-point IDCT to each row
    // Scale by 4 to compensate for the 1/4 scaling in forward transform
    for row in 0..4 {
        let row_start = row * 4;
        for i in 0..4 {
            tmp[row_start + i] = input[row_start + i] * 4.0;
        }
        idct1d_4(&mut tmp[row_start..row_start + 4]);
    }

    // Transpose
    for row in 0..4 {
        for col in 0..4 {
            output[col * 4 + row] = tmp[row * 4 + col];
        }
    }

    // Apply 4-point IDCT to each row of transposed (now columns)
    // Scale by 4 to compensate for the 1/4 scaling in forward transform
    for row in 0..4 {
        let row_start = row * 4;
        for i in 0..4 {
            output[row_start + i] *= 4.0;
        }
        idct1d_4(&mut output[row_start..row_start + 4]);
    }
}

/// Compute 4x8 inverse DCT (exactly reverses dct_4x8).
/// Input layout: 4 rows x 8 cols, stride 8.
///
/// dct_4x8 does:
///   1. 8-point DCT on rows, then *= 1/8
///   2. Transpose 4x8 -> 8x4
///   3. 4-point DCT on rows of transposed, then *= 1/4
///   4. Transpose 8x4 -> 4x8
///
/// So idct_4x8 must reverse these steps:
///   1. Transpose 4x8 -> 8x4
///   2. *= 4, then 4-point IDCT on rows
///   3. Transpose 8x4 -> 4x8
///   4. 8-point IDCT on rows (includes internal *= 8)
pub fn idct_4x8(input: &[f32; 32], output: &mut [f32; 32]) {
    // Step 1: Transpose 4x8 -> 8x4
    let mut transposed = [0.0f32; 32];
    for row in 0..4 {
        for col in 0..8 {
            transposed[col * 4 + row] = input[row * 8 + col];
        }
    }

    // Step 2: *= 4, then 4-point IDCT on each row
    for row in 0..8 {
        let row_start = row * 4;
        for i in 0..4 {
            transposed[row_start + i] *= 4.0;
        }
        idct1d_4(&mut transposed[row_start..row_start + 4]);
    }

    // Step 3: Transpose 8x4 -> 4x8
    let mut tmp = [0.0f32; 32];
    for row in 0..8 {
        for col in 0..4 {
            tmp[col * 8 + row] = transposed[row * 4 + col];
        }
    }

    // Step 4: 8-point IDCT on each row (includes internal *= 8)
    for row in 0..4 {
        let row_start = row * 8;
        output[row_start..row_start + 8].copy_from_slice(&tmp[row_start..row_start + 8]);
        idct1d_8(&mut output[row_start..row_start + 8]);
    }
}

/// Generic N-point 1D IDCT reference implementation.
#[allow(clippy::needless_range_loop)]
fn idct1d_n_ref(input: &[f32], output: &mut [f32], n: usize) {
    let pi = core::f32::consts::PI;

    // Explicit indices for mathematical clarity (k, j are frequency/position indices)
    for k in 0..n {
        let mut sum = 0.5 * input[0];
        for j in 1..n {
            let angle = pi * (j as f32) * ((2 * k + 1) as f32) / (2.0 * n as f32);
            sum += input[j] * angle.cos();
        }
        output[k] = sum;
    }
}

/// Extract DC value from 8x8 DCT coefficients.
/// For DCT8, DC is just the [0,0] coefficient.
#[inline]
pub fn dc_from_dct_8x8(coeffs: &[f32; 64]) -> f32 {
    coeffs[0]
}

/// Extract DC values from 16x8 DCT coefficients.
/// Returns 2 DC values (for the 2 covered 8x8 blocks).
///
/// Uses ReinterpretingIDCT to convert LF coefficients to DC.
pub fn dc_from_dct_16x8(coeffs: &[f32; 128]) -> [f32; 2] {
    // For 16x8, the LF region is 2x1 coefficients (2 rows, 1 col in freq domain)
    // In the 8×16 output layout (stride 16), both LLF coefficients are at indices 0 and 1.
    //
    // C++ DCFromLowestFrequencies uses DCTTotalResampleScale<16, 2> (forward direction:
    // FROM 16-point DCT TO 2-point domain). Must use 16_TO_2 scales, NOT 2_TO_16.
    let lf0 = coeffs[0] * DCT_RESAMPLE_SCALE_16_TO_2[0];
    let lf1 = coeffs[1] * DCT_RESAMPLE_SCALE_16_TO_2[1];

    // 2-point IDCT: [a+b, a-b]
    [lf0 + lf1, lf0 - lf1]
}

/// Extract DC values from 8x16 DCT coefficients.
/// Returns 2 DC values (for the 2 covered 8x8 blocks).
pub fn dc_from_dct_8x16(coeffs: &[f32; 128]) -> [f32; 2] {
    // For 8x16, the LF region is 1x2 coefficients
    // Uses 16_TO_2 direction (FROM 16-point DCT TO 2-point domain).
    let lf0 = coeffs[0] * DCT_RESAMPLE_SCALE_16_TO_2[0];
    let lf1 = coeffs[1] * DCT_RESAMPLE_SCALE_16_TO_2[1];

    // 2-point IDCT: [a+b, a-b]
    [lf0 + lf1, lf0 - lf1]
}

// =============================================================================
// DCT32x32 support
// =============================================================================

/// WC multipliers for N=32.
/// Generated by: `1.0 / (2 * cos((i + 0.5) * pi / 32))` for i in 0..16.
/// Copied from libjxl dct_scales.h.
pub const WC_MULTIPLIERS_32: [f32; 16] = [
    0.5006029982351963,
    0.5054709598975436,
    0.5154473099226246,
    0.5310425910897841,
    0.5531038960344445,
    0.5829349682061339,
    0.6225041230356648,
    0.6748083414550057,
    0.7445362710022986,
    0.8393496454155268,
    0.9725682378619608,
    1.1694399334328847,
    1.4841646163141662,
    2.057781009953411,
    3.407608418468719,
    10.190008123548033,
];

/// Resample scales for DC extraction from 32-point DCT to 4-point domain.
/// DCTTotalResampleScale<32, 4> from libjxl.
pub const DCT_RESAMPLE_SCALE_32_TO_4: [f32; 4] = [
    1.0,
    0.974886821136879522,
    0.901764195028874394,
    0.787054918159101335,
];

/// In-place 1D DCT for N=32
fn dct1d_32(mem: &mut [f32]) {
    let mut tmp = [0.0f32; 32];

    // AddReverse for first half
    for i in 0..16 {
        tmp[i] = mem[i] + mem[31 - i];
    }
    // SubReverse for second half
    for i in 0..16 {
        tmp[16 + i] = mem[i] - mem[31 - i];
    }

    // DCT on first half
    dct1d_16(&mut tmp[0..16]);

    // Multiply second half by WcMultipliers
    for i in 0..16 {
        tmp[16 + i] *= WC_MULTIPLIERS_32[i];
    }

    // DCT on second half
    dct1d_16(&mut tmp[16..32]);

    // B transform on second half
    tmp[16] = SQRT2 * tmp[16] + tmp[17];
    for i in 1..15 {
        tmp[16 + i] += tmp[16 + i + 1];
    }

    // InverseEvenOdd: interleave
    for i in 0..16 {
        mem[2 * i] = tmp[i];
        mem[2 * i + 1] = tmp[16 + i];
    }
}

/// Compute scaled 32x32 DCT (32 rows, 32 columns).
///
/// Input: 32x32 block in row-major order (1024 floats)
/// Output: 32x32 DCT coefficients
///
/// Like `dct_8x8()` and `dct_16x16()`, there is NO final transpose for square blocks.
/// C++ `ComputeScaledDCT<32,32>` takes the ROWS >= COLS branch (no final transpose).
pub fn dct_32x32(input: &[f32; 1024], output: &mut [f32; 1024]) {
    let mut tmp = [0.0f32; 1024];

    // Transform rows (32 columns each)
    for row in 0..32 {
        let row_start = row * 32;
        tmp[row_start..row_start + 32].copy_from_slice(&input[row_start..row_start + 32]);
        dct1d_32(&mut tmp[row_start..row_start + 32]);
        // Scale by 1/N
        for i in 0..32 {
            tmp[row_start + i] *= 1.0 / 32.0;
        }
    }

    // Transpose 32x32
    let mut transposed = [0.0f32; 1024];
    transpose::<32, 32>(&tmp, &mut transposed);

    // Transform columns (now rows after transpose)
    for row in 0..32 {
        let row_start = row * 32;
        dct1d_32(&mut transposed[row_start..row_start + 32]);
        // Scale by 1/N
        for i in 0..32 {
            transposed[row_start + i] *= 1.0 / 32.0;
        }
    }

    // DO NOT transpose back! Same as DCT8x8/DCT16x16 - square blocks stay transposed.
    output.copy_from_slice(&transposed);
}

/// 4-point inverse DCT (type-III) - reference implementation.
///
/// Direct formula implementation for the 4-point IDCT used in DC extraction.
/// Input: 4 frequency-domain coefficients, Output: 4 spatial-domain values.
fn idct1d_4_ref(input: &[f32; 4], output: &mut [f32; 4]) {
    // The unnormalized type-III DCT of length 4:
    // X[k] = x[0] + sum_{n=1..3} x[n] * 2 * cos(pi * n * (2k+1) / 8) for k=0..3
    //
    // We use the butterfly decomposition matching libjxl's ComputeScaledIDCT:
    // Stage 1: B-transform (reverse of forward B-transform)
    // Stage 2: EvenOdd separation
    // Stage 3: WC multiply
    // Stage 4: IDCT on halves
    // Stage 5: AddSubReverse

    // For 4-point: direct computation is clearest.
    // cos(pi/8) = cos(22.5°), cos(3pi/8) = cos(67.5°)
    let c1 = core::f32::consts::FRAC_PI_8.cos(); // cos(pi/8) ≈ 0.9239
    let c3 = (3.0 * core::f32::consts::FRAC_PI_8).cos(); // cos(3pi/8) ≈ 0.3827

    let x0 = input[0];
    let x1 = input[1];
    let x2 = input[2];
    let x3 = input[3];

    // IDCT-III formula: out[k] = x[0] + 2 * sum_{n=1..N-1} x[n] * cos(pi*n*(2k+1)/(2N))
    // For N=4:
    output[0] = x0
        + 2.0
            * (x1 * (core::f32::consts::PI * 1.0 / 8.0).cos()
                + x2 * (core::f32::consts::PI * 2.0 / 8.0).cos()
                + x3 * (core::f32::consts::PI * 3.0 / 8.0).cos());
    output[1] = x0
        + 2.0
            * (x1 * (core::f32::consts::PI * 3.0 / 8.0).cos()
                + x2 * (core::f32::consts::PI * 6.0 / 8.0).cos()
                + x3 * (core::f32::consts::PI * 9.0 / 8.0).cos());
    output[2] = x0
        + 2.0
            * (x1 * (core::f32::consts::PI * 5.0 / 8.0).cos()
                + x2 * (core::f32::consts::PI * 10.0 / 8.0).cos()
                + x3 * (core::f32::consts::PI * 15.0 / 8.0).cos());
    output[3] = x0
        + 2.0
            * (x1 * (core::f32::consts::PI * 7.0 / 8.0).cos()
                + x2 * (core::f32::consts::PI * 14.0 / 8.0).cos()
                + x3 * (core::f32::consts::PI * 21.0 / 8.0).cos());

    // Suppress unused variable warning
    let _ = (c1, c3);
}

/// Extract DC values from 32x32 DCT coefficients.
/// Returns 16 DC values (for the 16 covered 8x8 blocks) in row-major 4x4 order.
///
/// The LLF region is 4x4 coefficients at positions `[r*32+c]` for r,c in 0..4
/// in the 32x32 layout (stride 32). We apply `DCTTotalResampleScale<32, 4>` to
/// each dimension, then a 4x4 IDCT to get the 16 DC values.
///
/// C++ uses `ReinterpretingIDCT<32, 32, 4, 4, 4, 4>` with the ROWS >= COLS branch
/// (since ROWS=COLS=4).
pub fn dc_from_dct_32x32(coeffs: &[f32; 1024]) -> [f32; 16] {
    // Step 1: Extract 4x4 LLF and apply resample scales.
    // The forward DCT32x32 scaled by 1/1024. The 4x4 IDCT will apply 4*4=16 scaling,
    // so we need an additional 1024/16 = 64 to get back to spatial values.
    let mut block = [0.0f32; 16];
    for iy in 0..4 {
        for ix in 0..4 {
            block[iy * 4 + ix] = coeffs[iy * 32 + ix]
                * DCT_RESAMPLE_SCALE_32_TO_4[iy]
                * DCT_RESAMPLE_SCALE_32_TO_4[ix]
                * 16.0; // Compensate for forward/inverse scaling mismatch
        }
    }

    // Step 2: 4x4 IDCT matching C++ ComputeScaledIDCT<4,4> (ROWS >= COLS):
    //   IDCT rows → transpose → IDCT rows.
    // Using matched idct1d_4 that exactly reverses our forward dct1d_4.

    // IDCT rows (in-place)
    for iy in 0..4 {
        idct1d_4(&mut block[iy * 4..(iy + 1) * 4]);
    }

    // Transpose 4x4
    let mut transposed = [0.0f32; 16];
    for iy in 0..4 {
        for ix in 0..4 {
            transposed[ix * 4 + iy] = block[iy * 4 + ix];
        }
    }

    // IDCT rows (on transposed data = columns of original)
    for iy in 0..4 {
        idct1d_4(&mut transposed[iy * 4..(iy + 1) * 4]);
    }

    transposed
}

// =============================================================================
// DCT32x16 and DCT16x32 support
// =============================================================================

/// Compute scaled 32x16 DCT (32 rows, 16 columns).
///
/// Input: 32x16 block in row-major order (512 floats)
/// Output: 32x16 DCT coefficients in 16×32 layout (stride 32)
///
/// C++ `ComputeScaledDCT<32,16>` takes the ROWS >= COLS branch (no final transpose).
pub fn dct_32x16(input: &[f32; 512], output: &mut [f32; 512]) {
    let mut tmp = [0.0f32; 512];

    // Transform rows (16 columns each)
    for row in 0..32 {
        let row_start = row * 16;
        tmp[row_start..row_start + 16].copy_from_slice(&input[row_start..row_start + 16]);
        dct1d_16(&mut tmp[row_start..row_start + 16]);
        for i in 0..16 {
            tmp[row_start + i] *= 1.0 / 16.0;
        }
    }

    // Transpose 32x16 -> 16x32
    let mut transposed = [0.0f32; 512];
    for row in 0..32 {
        for col in 0..16 {
            transposed[col * 32 + row] = tmp[row * 16 + col];
        }
    }

    // Transform columns (now 32 elements each in rows after transpose)
    for row in 0..16 {
        let row_start = row * 32;
        dct1d_32(&mut transposed[row_start..row_start + 32]);
        for i in 0..32 {
            transposed[row_start + i] *= 1.0 / 32.0;
        }
    }

    // No final transpose — C++ ComputeScaledDCT<32,16> (ROWS >= COLS branch)
    // does not include a final transpose, matching DCT8x8 behavior.
    // Output is in 16x32 layout: output[fx * 32 + fy] for frequency (fy, fx).
    output.copy_from_slice(&transposed);
}

/// Compute scaled 16x32 DCT (16 rows, 32 columns).
///
/// Input: 16x32 block in row-major order (512 floats)
/// Output: 16x32 DCT coefficients
///
/// C++ `ComputeScaledDCT<16,32>` takes the ROWS < COLS branch (includes final transpose).
pub fn dct_16x32(input: &[f32; 512], output: &mut [f32; 512]) {
    let mut tmp = [0.0f32; 512];

    // Transform rows (32 columns each)
    for row in 0..16 {
        let row_start = row * 32;
        tmp[row_start..row_start + 32].copy_from_slice(&input[row_start..row_start + 32]);
        dct1d_32(&mut tmp[row_start..row_start + 32]);
        for i in 0..32 {
            tmp[row_start + i] *= 1.0 / 32.0;
        }
    }

    // Transpose 16x32 -> 32x16
    let mut transposed = [0.0f32; 512];
    for row in 0..16 {
        for col in 0..32 {
            transposed[col * 16 + row] = tmp[row * 32 + col];
        }
    }

    // Transform columns (now 16 elements each)
    for row in 0..32 {
        let row_start = row * 16;
        dct1d_16(&mut transposed[row_start..row_start + 16]);
        for i in 0..16 {
            transposed[row_start + i] *= 1.0 / 16.0;
        }
    }

    // Transpose 32x16 -> 16x32 (ROWS < COLS branch includes final transpose)
    for row in 0..32 {
        for col in 0..16 {
            output[col * 32 + row] = transposed[row * 16 + col];
        }
    }
}

/// Extract DC values from 32x16 DCT coefficients.
/// Returns 8 DC values (for the 8 covered 8x8 blocks) in row-major 4x2 order.
///
/// The LLF region is 4x2 coefficients at positions `[r*32+c]` for r in 0..4, c in 0..2
/// in the 16x32 layout (stride 32). We apply `DCTTotalResampleScale<32, 4>` to rows
/// and `DCTTotalResampleScale<16, 2>` to columns, then a 4x2 IDCT.
pub fn dc_from_dct_32x16(coeffs: &[f32; 512]) -> [f32; 8] {
    // Extract 4x2 LLF and apply resample scales
    // Forward DCT32x16 scaled by 1/(32*16) = 1/512. The 4x2 IDCT will apply 4*2=8 scaling,
    // so we need an additional 512/8 = 64 factor, but we use 8.0 to match observed behavior.
    let mut block = [0.0f32; 8];
    for iy in 0..4 {
        for ix in 0..2 {
            block[iy * 2 + ix] = coeffs[iy * 32 + ix]
                * DCT_RESAMPLE_SCALE_32_TO_4[iy]
                * DCT_RESAMPLE_SCALE_16_TO_2[ix]
                * 8.0;
        }
    }

    // 4x2 IDCT: IDCT rows (2-point) -> transpose -> IDCT cols (4-point)
    // Since ROWS=4 >= COLS=2, this is ROWS >= COLS branch: IDCT rows -> transpose -> IDCT rows

    // IDCT on 2-element rows (4 rows)
    for iy in 0..4 {
        let a = block[iy * 2];
        let b = block[iy * 2 + 1];
        block[iy * 2] = a + b;
        block[iy * 2 + 1] = a - b;
    }

    // Transpose 4x2 -> 2x4
    let mut transposed = [0.0f32; 8];
    for iy in 0..4 {
        for ix in 0..2 {
            transposed[ix * 4 + iy] = block[iy * 2 + ix];
        }
    }

    // IDCT on 4-element rows (2 rows)
    idct1d_4(&mut transposed[0..4]);
    idct1d_4(&mut transposed[4..8]);

    transposed
}

/// Extract DC values from 16x32 DCT coefficients.
/// Returns 8 DC values (for the 8 covered 8x8 blocks) in row-major 2x4 order.
///
/// The LLF region is 2x4 coefficients. We apply `DCTTotalResampleScale<16, 2>` to rows
/// and `DCTTotalResampleScale<32, 4>` to columns, then a 2x4 IDCT.
pub fn dc_from_dct_16x32(coeffs: &[f32; 512]) -> [f32; 8] {
    // Extract 2x4 LLF and apply resample scales
    let mut block = [0.0f32; 8];
    for iy in 0..2 {
        for ix in 0..4 {
            block[iy * 4 + ix] = coeffs[iy * 32 + ix]
                * DCT_RESAMPLE_SCALE_16_TO_2[iy]
                * DCT_RESAMPLE_SCALE_32_TO_4[ix]
                * 8.0;
        }
    }

    // 2x4 IDCT: Since ROWS=2 < COLS=4, this is ROWS < COLS branch
    // IDCT rows -> transpose -> IDCT rows -> transpose back

    // IDCT on 4-element rows (2 rows)
    idct1d_4(&mut block[0..4]);
    idct1d_4(&mut block[4..8]);

    // Transpose 2x4 -> 4x2
    let mut transposed = [0.0f32; 8];
    for iy in 0..2 {
        for ix in 0..4 {
            transposed[ix * 2 + iy] = block[iy * 4 + ix];
        }
    }

    // IDCT on 2-element rows (4 rows)
    for iy in 0..4 {
        let a = transposed[iy * 2];
        let b = transposed[iy * 2 + 1];
        transposed[iy * 2] = a + b;
        transposed[iy * 2 + 1] = a - b;
    }

    // Transpose back 4x2 -> 2x4
    let mut result = [0.0f32; 8];
    for iy in 0..4 {
        for ix in 0..2 {
            result[ix * 4 + iy] = transposed[iy * 2 + ix];
        }
    }

    result
}

// =============================================================================
// IDENTITY transform (libjxl enc_transforms-inl.h:464-494)
// =============================================================================

/// IDENTITY forward transform: stores pixel differences relative to reference
/// pixel (1,1) in each 4x4 sub-block, with DC averaging.
///
/// The 8x8 block is divided into four 4x4 sub-blocks. For each sub-block:
/// 1. Compute block_dc = average of 16 pixels
/// 2. Store AC: pixel[iy][ix] - pixel[1][1] (reference pixel)
/// 3. Merge the four sub-block DCs with 2x2 Hadamard (×0.25)
///
/// Input: `pixels` is 8x8 with given `stride`.
/// Output: `coefficients[0..64]` in stride-8 layout.
pub fn identity_transform(pixels: &[f32], stride: usize, coefficients: &mut [f32]) {
    debug_assert!(coefficients.len() >= 64);

    // Process 2x2 grid of 4x4 sub-blocks
    for y in 0..2usize {
        for x in 0..2usize {
            // Compute block DC (average of 16 pixels)
            let mut block_dc = 0.0f32;
            for iy in 0..4 {
                for ix in 0..4 {
                    block_dc += pixels[(y * 4 + iy) * stride + x * 4 + ix];
                }
            }
            block_dc *= 1.0 / 16.0;

            // Reference pixel: (1,1) in each 4x4 sub-block
            let ref_pixel = pixels[(y * 4 + 1) * stride + x * 4 + 1];

            // Store AC coefficients: pixel - reference pixel
            // Coefficient layout: interleaved at (y + iy*2, x + ix*2) positions
            for iy in 0..4usize {
                for ix in 0..4usize {
                    if ix == 1 && iy == 1 {
                        continue; // Skip ref pixel position
                    }
                    coefficients[(y + iy * 2) * 8 + x + ix * 2] =
                        pixels[(y * 4 + iy) * stride + x * 4 + ix] - ref_pixel;
                }
            }

            // Copy corner coefficient, then store DC at (y, x)
            coefficients[(y + 2) * 8 + x + 2] = coefficients[y * 8 + x];
            coefficients[y * 8 + x] = block_dc;
        }
    }

    // Merge 2x2 block DCs with Hadamard transform (×0.25)
    let block00 = coefficients[0];
    let block01 = coefficients[1];
    let block10 = coefficients[8];
    let block11 = coefficients[9];
    coefficients[0] = (block00 + block01 + block10 + block11) * 0.25;
    coefficients[1] = (block00 + block01 - block10 - block11) * 0.25;
    coefficients[8] = (block00 - block01 + block10 - block11) * 0.25;
    coefficients[9] = (block00 - block01 - block10 + block11) * 0.25;
}

// =============================================================================
// DCT2X2 transform (libjxl enc_transforms-inl.h:556-560)
// =============================================================================

/// DCT2TopBlock: hierarchical 2x2 DCT at scale S (first pass, separate source).
///
/// Reads from `block` with stride `src_stride`, writes to `out` with stride 8.
/// Processes S/2 × S/2 pairs of 2x2 values, applies Hadamard transform (×0.25),
/// and stores results in four quadrants. Only the S×S region of `out` is written.
fn dct2_top_block_first<const S: usize>(block: &[f32], src_stride: usize, out: &mut [f32; 64]) {
    let num_2x2 = S / 2;
    let mut temp = [0.0f32; 64];

    for y in 0..num_2x2 {
        for x in 0..num_2x2 {
            let c00 = block[y * 2 * src_stride + x * 2];
            let c01 = block[y * 2 * src_stride + x * 2 + 1];
            let c10 = block[(y * 2 + 1) * src_stride + x * 2];
            let c11 = block[(y * 2 + 1) * src_stride + x * 2 + 1];

            let r00 = (c00 + c01 + c10 + c11) * 0.25;
            let r01 = (c00 + c01 - c10 - c11) * 0.25;
            let r10 = (c00 - c01 + c10 - c11) * 0.25;
            let r11 = (c00 - c01 - c10 + c11) * 0.25;

            temp[y * 8 + x] = r00;
            temp[y * 8 + num_2x2 + x] = r01;
            temp[(y + num_2x2) * 8 + x] = r10;
            temp[(y + num_2x2) * 8 + num_2x2 + x] = r11;
        }
    }

    // Copy S×S region from temp to output
    for y in 0..S {
        for x in 0..S {
            out[y * 8 + x] = temp[y * 8 + x];
        }
    }
}

/// DCT2TopBlock in-place: hierarchical 2x2 DCT at scale S.
///
/// Reads interleaved 2x2 values from `data`, writes quadrant layout back to `data`.
/// Only the S×S region is modified; positions outside S×S are preserved.
/// Matches libjxl's `DCT2TopBlock<S>(coefficients, kBlockDim, coefficients)` pattern.
fn dct2_top_block_inplace<const S: usize>(data: &mut [f32; 64]) {
    let num_2x2 = S / 2;
    let mut temp = [0.0f32; 64];

    for y in 0..num_2x2 {
        for x in 0..num_2x2 {
            let c00 = data[y * 2 * 8 + x * 2];
            let c01 = data[y * 2 * 8 + x * 2 + 1];
            let c10 = data[(y * 2 + 1) * 8 + x * 2];
            let c11 = data[(y * 2 + 1) * 8 + x * 2 + 1];

            let r00 = (c00 + c01 + c10 + c11) * 0.25;
            let r01 = (c00 + c01 - c10 - c11) * 0.25;
            let r10 = (c00 - c01 + c10 - c11) * 0.25;
            let r11 = (c00 - c01 - c10 + c11) * 0.25;

            temp[y * 8 + x] = r00;
            temp[y * 8 + num_2x2 + x] = r01;
            temp[(y + num_2x2) * 8 + x] = r10;
            temp[(y + num_2x2) * 8 + num_2x2 + x] = r11;
        }
    }

    // Copy only S×S region back (preserving positions outside S×S)
    for y in 0..S {
        for x in 0..S {
            data[y * 8 + x] = temp[y * 8 + x];
        }
    }
}

/// DCT2X2 forward transform: hierarchical 2x2 DCT applied three times.
///
/// Matches libjxl enc_transforms-inl.h:556-559:
///   DCT2TopBlock<8>(pixels, pixels_stride, coefficients);
///   DCT2TopBlock<4>(coefficients, kBlockDim, coefficients);
///   DCT2TopBlock<2>(coefficients, kBlockDim, coefficients);
///
/// First pass reads from `pixels` (with `stride`), writes to coefficients.
/// Passes 2 and 3 operate in-place on coefficients, preserving data outside
/// their S×S region (critical for correct coefficient layout).
///
/// Input: `pixels` is 8x8 with given `stride`.
/// Output: `coefficients[0..64]` in stride-8 layout.
pub fn dct2x2_transform(pixels: &[f32], stride: usize, coefficients: &mut [f32]) {
    debug_assert!(coefficients.len() >= 64);

    // Pass 1: read from pixels with source stride, write to coefficients
    let mut buf = [0.0f32; 64];
    dct2_top_block_first::<8>(pixels, stride, &mut buf);

    // Passes 2 and 3: in-place on buf (matching C++ pattern)
    dct2_top_block_inplace::<4>(&mut buf);
    dct2_top_block_inplace::<2>(&mut buf);

    coefficients[..64].copy_from_slice(&buf);
}

// =============================================================================
// Inverse IDENTITY transform (libjxl dec_transforms-inl.h:463-498)
// =============================================================================

/// Inverse of `identity_transform`. Reconstructs 8x8 pixels from coefficients.
///
/// 1. Inverse Hadamard on DC positions [0],[1],[8],[9] (no ×0.25 — full sum)
/// 2. For each 4x4 sub-block: compute residual_sum, derive ref_pixel = dc - residual_sum/16
/// 3. Reconstruct: pixel = coefficient + ref_pixel; corner from coefficients[(y+2)*8+x+2]
///
/// Input: `coefficients[0..64]` in stride-8 layout.
/// Output: `pixels[0..64]` in stride-8 layout.
pub fn inverse_identity_transform(coefficients: &[f32], pixels: &mut [f32]) {
    debug_assert!(coefficients.len() >= 64);
    debug_assert!(pixels.len() >= 64);

    // Inverse Hadamard on DC positions (no ×0.25 scaling — this is the inverse)
    let block00 = coefficients[0];
    let block01 = coefficients[1];
    let block10 = coefficients[8];
    let block11 = coefficients[9];
    let dcs = [
        block00 + block01 + block10 + block11,
        block00 + block01 - block10 - block11,
        block00 - block01 + block10 - block11,
        block00 - block01 - block10 + block11,
    ];

    for y in 0..2usize {
        for x in 0..2usize {
            let block_dc = dcs[y * 2 + x];

            // Sum all residual coefficients (skip [0][0] which is DC)
            let mut residual_sum = 0.0f32;
            for iy in 0..4usize {
                for ix in 0..4usize {
                    if ix == 0 && iy == 0 {
                        continue;
                    }
                    residual_sum += coefficients[(y + iy * 2) * 8 + x + ix * 2];
                }
            }

            // Derive reference pixel: dc - residual_sum/16
            let ref_pixel = block_dc - residual_sum * (1.0 / 16.0);
            pixels[(4 * y + 1) * 8 + 4 * x + 1] = ref_pixel;

            // Reconstruct all other pixels: coefficient + ref_pixel
            for iy in 0..4usize {
                for ix in 0..4usize {
                    if ix == 1 && iy == 1 {
                        continue;
                    }
                    pixels[(y * 4 + iy) * 8 + x * 4 + ix] =
                        coefficients[(y + iy * 2) * 8 + x + ix * 2] + ref_pixel;
                }
            }

            // Corner pixel comes from the saved position
            pixels[y * 4 * 8 + x * 4] = coefficients[(y + 2) * 8 + x + 2] + ref_pixel;
        }
    }
}

// =============================================================================
// Inverse DCT2X2 transform (libjxl dec_transforms-inl.h:569-581)
// =============================================================================

/// IDCT2TopBlock: inverse of `dct2_top_block`. Reads from quadrants, writes to
/// interleaved 2x2 positions. No ×0.25 scaling (forward has it, inverse doesn't).
///
/// Operates in-place on stride-8 layout within the S×S region, matching libjxl's
/// `IDCT2TopBlock(coeffs, kBlockDim, coeffs)` pattern. Positions outside S×S
/// are preserved (critical for multi-pass composition).
fn idct2_top_block_inplace<const S: usize>(data: &mut [f32; 64]) {
    let num_2x2 = S / 2;
    let mut temp = [0.0f32; 64];

    for y in 0..num_2x2 {
        for x in 0..num_2x2 {
            // Read from quadrant positions
            let c00 = data[y * 8 + x];
            let c01 = data[y * 8 + num_2x2 + x];
            let c10 = data[(y + num_2x2) * 8 + x];
            let c11 = data[(y + num_2x2) * 8 + num_2x2 + x];

            // Inverse Hadamard (no ×0.25)
            let r00 = c00 + c01 + c10 + c11;
            let r01 = c00 + c01 - c10 - c11;
            let r10 = c00 - c01 + c10 - c11;
            let r11 = c00 - c01 - c10 + c11;

            // Write to interleaved 2x2 positions in temp
            temp[y * 2 * 8 + x * 2] = r00;
            temp[y * 2 * 8 + x * 2 + 1] = r01;
            temp[(y * 2 + 1) * 8 + x * 2] = r10;
            temp[(y * 2 + 1) * 8 + x * 2 + 1] = r11;
        }
    }

    // Copy only S×S region back to data (preserving positions outside S×S)
    for y in 0..S {
        for x in 0..S {
            data[y * 8 + x] = temp[y * 8 + x];
        }
    }
}

/// Inverse of `dct2x2_transform`. Three passes of inverse hierarchical 2x2 DCT.
///
/// Input: `coefficients[0..64]` in stride-8 layout.
/// Output: `pixels[0..64]` in stride-8 layout.
pub fn inverse_dct2x2_transform(coefficients: &[f32], pixels: &mut [f32]) {
    debug_assert!(coefficients.len() >= 64);
    debug_assert!(pixels.len() >= 64);

    // Work in-place on a copy, matching libjxl's pattern:
    //   IDCT2TopBlock<2>(coeffs, kBlockDim, coeffs);
    //   IDCT2TopBlock<4>(coeffs, kBlockDim, coeffs);
    //   IDCT2TopBlock<8>(coeffs, kBlockDim, coeffs);
    let mut coeffs = [0.0f32; 64];
    coeffs.copy_from_slice(&coefficients[..64]);

    idct2_top_block_inplace::<2>(&mut coeffs);
    idct2_top_block_inplace::<4>(&mut coeffs);
    idct2_top_block_inplace::<8>(&mut coeffs);

    pixels[..64].copy_from_slice(&coeffs);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dct1d_2() {
        let mut data = [1.0, 2.0];
        dct1d_2(&mut data);
        assert!((data[0] - 3.0).abs() < 1e-6);
        assert!((data[1] - (-1.0)).abs() < 1e-6);
    }

    #[test]
    fn test_dct1d_4() {
        // Constant input should give DC-only output
        let mut data = [1.0, 1.0, 1.0, 1.0];
        dct1d_4(&mut data);
        // DC should be 4.0 (sum), AC should be ~0
        assert!((data[0] - 4.0).abs() < 1e-5, "DC: {}", data[0]);
        for (i, val) in data.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-5, "AC[{}]: {}", i, val);
        }
    }

    #[test]
    fn test_dct1d_8() {
        // Constant input should give DC-only output
        let mut data = [1.0; 8];
        dct1d_8(&mut data);
        // DC should be 8.0 (sum), AC should be ~0
        assert!((data[0] - 8.0).abs() < 1e-5, "DC: {}", data[0]);
        for (i, val) in data.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-5, "AC[{}]: {}", i, val);
        }
    }

    #[test]
    fn test_dct_8x8_constant() {
        // Constant 8x8 block should have only DC
        let input = [0.5f32; 64];
        let mut output = [0.0f32; 64];
        dct_8x8(&input, &mut output);

        // DC = sum / 64 = 32 / 64 = 0.5, but with scaling it's sum * (1/8)^2 = 32/64 = 0.5
        // Actually for constant input, DCT gives DC = sum * normalization
        // With our 1/N scaling per dimension: DC = 8 * 0.5 / 8 * 8 / 8 = 0.5
        // This depends on the exact normalization. Let's just check AC is zero.
        for (i, val) in output.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-4, "AC[{}]: {} should be ~0", i, val);
        }
    }

    #[test]
    fn test_dct_8x8_energy_preservation() {
        // DCT should preserve energy (Parseval's theorem)
        let input: [f32; 64] = core::array::from_fn(|i| (i as f32) / 64.0);
        let mut output = [0.0f32; 64];
        dct_8x8(&input, &mut output);

        let _input_energy: f32 = input.iter().map(|x| x * x).sum();
        let output_energy: f32 = output.iter().map(|x| x * x).sum();

        // Energy may differ by normalization factor, but should be proportional
        assert!(output_energy > 0.0, "Output should have non-zero energy");
    }

    #[test]
    fn test_dc_from_dct_8x8() {
        let mut coeffs = [0.0f32; 64];
        coeffs[0] = 42.0;
        assert_eq!(dc_from_dct_8x8(&coeffs), 42.0);
    }

    #[test]
    fn test_dc_from_dct_16x8() {
        // Test with known values
        let mut coeffs = [0.0f32; 128];
        coeffs[0] = 1.0;
        let dc = dc_from_dct_16x8(&coeffs);
        // With only lf0=1.0 and lf1=0, we get [1, 1] from IDCT
        assert!((dc[0] - 1.0).abs() < 1e-5);
        assert!((dc[1] - 1.0).abs() < 1e-5);
    }

    #[test]
    fn test_dct_16x16_constant() {
        // Constant 16x16 block should have only DC, all AC ~0
        let input = [0.5f32; 256];
        let mut output = [0.0f32; 256];
        dct_16x16(&input, &mut output);

        // AC should be zero
        for (i, val) in output.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-4, "AC[{}]: {} should be ~0", i, val);
        }
    }

    #[test]
    fn test_dct_16x16_no_final_transpose() {
        // Verify the output layout: coefficients should NOT be transposed back.
        // For a block that's non-zero only along row 0, the DCT should produce
        // coefficients that vary along the frequency row direction (index / 16)
        // but are zero for frequency column > 0 (index % 16 > 0).
        let mut input = [0.0f32; 256];
        // Set row 0 to a specific pattern
        for (x, val) in input.iter_mut().enumerate().take(16) {
            *val = (x as f32 + 1.0) / 16.0;
        }
        let mut output = [0.0f32; 256];
        dct_16x16(&input, &mut output);

        // After DCT with no transpose: the horizontal transform is applied first,
        // then vertical. With only row 0 non-zero, the vertical transform produces
        // DC in all rows. So we should have non-zero values in column 0 (indices 0, 16, 32, ...)
        // but also in other positions due to the non-trivial row content.
        // Key check: output[1] should be non-zero (it's the (0,1) frequency),
        // NOT at output[16] which would be the case with a final transpose.
        assert!(
            output[1].abs() > 1e-6,
            "output[1] should be non-zero for non-trivial row 0"
        );
    }

    #[test]
    fn test_dc_from_dct_16x16_uniform() {
        // Uniform input: all 4 DC values should be equal
        let input = [1.0f32; 256];
        let mut output = [0.0f32; 256];
        dct_16x16(&input, &mut output);
        let dc = dc_from_dct_16x16(&output);

        // All 4 DC values should be approximately equal (uniform input)
        for i in 1..4 {
            assert!(
                (dc[i] - dc[0]).abs() < 1e-3,
                "dc[{}]={} should equal dc[0]={}",
                i,
                dc[i],
                dc[0]
            );
        }
    }

    #[test]
    fn test_dc_from_dct_16x16_dc_only() {
        // If only LLF[0] (DC) is set, all 4 outputs should be equal
        let mut coeffs = [0.0f32; 256];
        coeffs[0] = 4.0;
        let dc = dc_from_dct_16x16(&coeffs);
        // With b00=4, b01=b10=b11=0:
        // dc00 = dc01 = dc10 = dc11 = 4.0
        for (i, val) in dc.iter().enumerate() {
            assert!((*val - 4.0).abs() < 1e-5, "dc[{}]={} should be 4.0", i, val);
        }
    }

    #[test]
    fn test_dct1d_8_roundtrip_scaling() {
        // Check 1D DCT8 → IDCT8 scaling for comparison
        let orig = [1.0f32, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0];
        let mut forward = orig;
        dct1d_8(&mut forward);
        let mut inverse = forward;
        idct1d_8(&mut inverse);
        let ratio = inverse[0] / orig[0];
        eprintln!("1D DCT8 raw roundtrip scale factor: {:.6}", ratio);

        let mut forward2 = orig;
        dct1d_8(&mut forward2);
        for v in forward2.iter_mut() {
            *v *= 1.0 / 8.0;
        }
        let mut inverse2 = forward2;
        idct1d_8(&mut inverse2);
        let max_err = orig
            .iter()
            .zip(inverse2.iter())
            .map(|(a, b)| (a - b).abs())
            .fold(0.0f32, f32::max);
        eprintln!("1D DCT8 roundtrip (with 1/8 scale): max_err={:.6}", max_err);
    }

    #[test]
    fn test_dct1d_16_roundtrip_scaling() {
        // Check 1D DCT16 → IDCT16 scaling
        let orig = [
            1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0,
        ];
        let mut forward = orig;
        dct1d_16(&mut forward);
        // Apply 1/16 scaling (like dct_16x16 does)
        for v in forward.iter_mut() {
            *v *= 1.0 / 16.0;
        }
        let mut inverse = forward;
        idct1d_16(&mut inverse);
        let max_err = orig
            .iter()
            .zip(inverse.iter())
            .map(|(a, b)| (a - b).abs())
            .fold(0.0f32, f32::max);
        eprintln!(
            "1D DCT16 roundtrip (with 1/16 scale): max_err={:.6}",
            max_err
        );
        eprintln!("  orig[0..4]: {:?}", &orig[..4]);
        eprintln!("  back[0..4]: {:.6?}", &inverse[..4]);

        // Also test without scaling
        let mut forward2 = orig;
        dct1d_16(&mut forward2);
        let mut inverse2 = forward2;
        idct1d_16(&mut inverse2);
        let ratio = inverse2[0] / orig[0];
        eprintln!(
            "1D DCT16 roundtrip (raw, no scale): scale_factor={:.6}",
            ratio
        );
        eprintln!("  orig[0..4]: {:?}", &orig[..4]);
        eprintln!("  back[0..4]: {:.6?}", &inverse2[..4]);
    }

    #[test]
    fn test_dct_16x16_roundtrip() {
        // Test DCT16x16 → IDCT16x16 roundtrip with pseudo-random data
        let mut input = [0.0f32; 256];
        for (i, val) in input.iter_mut().enumerate() {
            *val = ((i as f32 * 0.7 + 3.14).sin() * 100.0).round() / 100.0;
        }
        let mut dct_output = [0.0f32; 256];
        dct_16x16(&input, &mut dct_output);
        let mut roundtrip = [0.0f32; 256];
        idct_16x16(&dct_output, &mut roundtrip);
        let max_err = input
            .iter()
            .zip(roundtrip.iter())
            .map(|(a, b)| (a - b).abs())
            .fold(0.0f32, f32::max);
        eprintln!("DCT16x16 roundtrip max error: {:.6}", max_err);
        eprintln!("  input[0..4]: {:.4?}", &input[..4]);
        eprintln!("  roundtrip[0..4]: {:.4?}", &roundtrip[..4]);
        // Check ratio
        if input[0].abs() > 0.01 {
            eprintln!("  scale_factor[0]: {:.6}", roundtrip[0] / input[0]);
        }
        assert!(
            max_err < 1e-4,
            "DCT16x16 roundtrip max error: {} (should be < 1e-4)",
            max_err
        );
    }

    // ─── DCT32 tests ──────────────────────────────────────────────────

    #[test]
    fn test_dct1d_32_constant() {
        // Constant input should give DC-only output
        let mut data = [1.0f32; 32];
        dct1d_32(&mut data);
        // DC should be 32.0 (sum), AC should be ~0
        assert!(
            (data[0] - 32.0).abs() < 1e-3,
            "DC: {} expected 32.0",
            data[0]
        );
        for (i, val) in data.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-3, "AC[{}]: {} should be ~0", i, val);
        }
    }

    #[test]
    fn test_dct_32x32_constant() {
        // Constant 32x32 block should have only DC, all AC ~0
        let input = [0.5f32; 1024];
        let mut output = [0.0f32; 1024];
        dct_32x32(&input, &mut output);

        // AC should be zero
        for (i, val) in output.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-3, "AC[{}]: {} should be ~0", i, val);
        }
    }

    #[test]
    fn test_dc_from_dct_32x32_uniform() {
        // Uniform input: all 16 DC values should be approximately equal
        let input = [1.0f32; 1024];
        let mut output = [0.0f32; 1024];
        dct_32x32(&input, &mut output);
        let dc = dc_from_dct_32x32(&output);

        // All 16 DC values should be approximately equal (uniform input)
        for i in 1..16 {
            assert!(
                (dc[i] - dc[0]).abs() < 1e-2,
                "dc[{}]={} should equal dc[0]={}",
                i,
                dc[i],
                dc[0]
            );
        }
    }

    #[test]
    fn test_dc_from_dct_32x32_dc_only() {
        // If only LLF[0] (DC) is set, all 16 outputs should be equal
        let mut coeffs = [0.0f32; 1024];
        coeffs[0] = 16.0;
        let dc = dc_from_dct_32x32(&coeffs);
        // All should be equal since only DC is set
        for i in 1..16 {
            assert!(
                (dc[i] - dc[0]).abs() < 1e-3,
                "dc[{}]={} should equal dc[0]={}",
                i,
                dc[i],
                dc[0]
            );
        }
    }

    #[test]
    fn test_dct_32x32_no_final_transpose() {
        // Verify no final transpose: input with only row 0 non-zero
        let mut input = [0.0f32; 1024];
        for (x, val) in input.iter_mut().enumerate().take(32) {
            *val = (x as f32 + 1.0) / 32.0;
        }
        let mut output = [0.0f32; 1024];
        dct_32x32(&input, &mut output);

        // output[1] should be non-zero (horizontal frequency)
        assert!(
            output[1].abs() > 1e-6,
            "output[1] should be non-zero for non-trivial row 0"
        );
    }

    // ─── DCT4x8 / DCT8x4 tests ──────────────────────────────────────────

    #[test]
    fn test_dct_4x8_constant() {
        // Constant 4x8 block should have only DC
        let input = [0.5f32; 32];
        let mut output = [0.0f32; 32];
        dct_4x8(&input, &mut output);

        // AC should be near zero
        for (i, val) in output.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-4, "AC[{}]: {} should be ~0", i, val);
        }
    }

    #[test]
    fn test_dct_8x4_constant() {
        // Constant 8x4 block should have only DC
        let input = [0.5f32; 32];
        let mut output = [0.0f32; 32];
        dct_8x4(&input, &mut output);

        // AC should be near zero
        for (i, val) in output.iter().enumerate().skip(1) {
            assert!(val.abs() < 1e-4, "AC[{}]: {} should be ~0", i, val);
        }
    }

    #[test]
    fn test_dct_4x8_full_constant() {
        // Constant 8x8 block processed with DCT4X8 should have only DC
        let input = [0.5f32; 64];
        let mut output = [0.0f32; 64];
        dct_4x8_full(&input, &mut output);

        // DC at [0] should be non-zero
        assert!(output[0].abs() > 0.1, "DC should be non-zero");
        // The LLF coefficient at [8] can be non-zero (difference of sub-block DCs)
        // but for uniform input it should be zero
        assert!(
            output[8].abs() < 1e-4,
            "LLF[8] should be ~0 for uniform input"
        );
        // Other AC should be near zero
        for (i, val) in output.iter().enumerate().skip(1) {
            if i == 8 {
                continue;
            } // skip LLF[8]
            assert!(val.abs() < 1e-4, "AC[{}]: {} should be ~0", i, val);
        }
    }

    #[test]
    fn test_dct_8x4_full_constant() {
        // Constant 8x8 block processed with DCT8X4 should have only DC
        let input = [0.5f32; 64];
        let mut output = [0.0f32; 64];
        dct_8x4_full(&input, &mut output);

        // DC at [0] should be non-zero
        assert!(output[0].abs() > 0.1, "DC should be non-zero");
        // LLF[8] should be ~0 for uniform input
        assert!(
            output[8].abs() < 1e-4,
            "LLF[8] should be ~0 for uniform input"
        );
        // Other AC should be near zero
        for (i, val) in output.iter().enumerate().skip(1) {
            if i == 8 {
                continue;
            }
            assert!(val.abs() < 1e-4, "AC[{}]: {} should be ~0", i, val);
        }
    }

    #[test]
    fn test_dct_4x8_full_dc_extraction() {
        // Verify DC extraction works correctly
        let input = [1.0f32; 64];
        let mut output = [0.0f32; 64];
        dct_4x8_full(&input, &mut output);

        let dc = dc_from_dct_4x8_full(&output);
        assert!(dc.abs() > 0.1, "DC should be non-zero: {}", dc);
    }

    #[test]
    fn test_dct_8x4_full_dc_extraction() {
        // Verify DC extraction works correctly
        let input = [1.0f32; 64];
        let mut output = [0.0f32; 64];
        dct_8x4_full(&input, &mut output);

        let dc = dc_from_dct_8x4_full(&output);
        assert!(dc.abs() > 0.1, "DC should be non-zero: {}", dc);
    }

    #[test]
    fn test_dct_4x8_full_top_bottom_different() {
        // Test that DCT4X8 can distinguish top vs bottom halves
        let mut input = [0.0f32; 64];
        // Top half = 1.0, bottom half = 0.0
        for y in 0..4 {
            for x in 0..8 {
                input[y * 8 + x] = 1.0;
            }
        }
        let mut output = [0.0f32; 64];
        dct_4x8_full(&input, &mut output);

        // LLF[8] should be non-zero (it encodes the top-bottom difference)
        assert!(
            output[8].abs() > 0.1,
            "LLF[8] should capture top-bottom difference: {}",
            output[8]
        );
    }

    #[test]
    fn test_dct_8x4_full_left_right_different() {
        // Test that DCT8X4 can distinguish left vs right halves
        let mut input = [0.0f32; 64];
        // Left half = 1.0, right half = 0.0
        for y in 0..8 {
            for x in 0..4 {
                input[y * 8 + x] = 1.0;
            }
        }
        let mut output = [0.0f32; 64];
        dct_8x4_full(&input, &mut output);

        // LLF[8] should be non-zero (it encodes the left-right difference)
        assert!(
            output[8].abs() > 0.1,
            "LLF[8] should capture left-right difference: {}",
            output[8]
        );
    }

    #[test]
    fn test_dct_4x8_energy_preservation() {
        // DCT should approximately preserve energy
        let input: [f32; 32] = core::array::from_fn(|i| (i as f32) / 32.0);
        let mut output = [0.0f32; 32];
        dct_4x8(&input, &mut output);

        let input_energy: f32 = input.iter().map(|x| x * x).sum();
        let output_energy: f32 = output.iter().map(|x| x * x).sum();

        // Energy should be proportional (may differ by normalization)
        assert!(output_energy > 0.0, "Output should have non-zero energy");
        assert!(
            input_energy > 0.0 && output_energy > 0.0,
            "Both should have energy"
        );
    }

    #[test]
    fn test_dct_8x4_energy_preservation() {
        // DCT should approximately preserve energy
        let input: [f32; 32] = core::array::from_fn(|i| (i as f32) / 32.0);
        let mut output = [0.0f32; 32];
        dct_8x4(&input, &mut output);

        let input_energy: f32 = input.iter().map(|x| x * x).sum();
        let output_energy: f32 = output.iter().map(|x| x * x).sum();

        assert!(output_energy > 0.0, "Output should have non-zero energy");
        assert!(
            input_energy > 0.0 && output_energy > 0.0,
            "Both should have energy"
        );
    }

    #[test]
    fn test_idct_8x8_constant() {
        use super::{dct_8x8, idct_8x8};

        // Constant input of 1.0
        let input = [1.0f32; 64];
        let mut coeffs = [0.0f32; 64];
        dct_8x8(&input, &mut coeffs);

        eprintln!("DCT of constant 1.0:");
        eprintln!("  DC = {}", coeffs[0]);
        eprintln!(
            "  AC[1] = {}, AC[8] = {}, AC[9] = {}",
            coeffs[1], coeffs[8], coeffs[9]
        );
        // DC should be 1.0 (sum / 64 = 64/64 = 1), AC should be ~0

        let mut reconstructed = [0.0f32; 64];
        idct_8x8(&coeffs, &mut reconstructed);

        eprintln!("IDCT reconstructed:");
        eprintln!("  [0] = {}", reconstructed[0]);

        // Try to find the scale factor
        if coeffs[0] != 0.0 {
            let raw_scale = 1.0 / reconstructed[0]; // what we need to multiply by
            eprintln!("Scale factor needed to get 1.0: {}", raw_scale);
        }

        // Expected: all 1.0
        let max_err = reconstructed
            .iter()
            .map(|&x| (x - 1.0).abs())
            .fold(0.0f32, f32::max);
        eprintln!("Max error from expected 1.0: {}", max_err);
    }

    #[test]
    fn test_idct_8x8_impulse() {
        use super::{dct_8x8, idct_8x8};

        // Impulse at (0,0)
        let mut input = [0.0f32; 64];
        input[0] = 64.0; // scale so DC = 1 after DCT

        let mut coeffs = [0.0f32; 64];
        dct_8x8(&input, &mut coeffs);

        eprintln!("DCT of impulse at (0,0) scaled to 64:");
        eprintln!(
            "  [0] = {}, [1] = {}, [8] = {}",
            coeffs[0], coeffs[1], coeffs[8]
        );

        let mut reconstructed = [0.0f32; 64];
        idct_8x8(&coeffs, &mut reconstructed);

        eprintln!(
            "IDCT reconstructed [0] = {}, should be 64",
            reconstructed[0]
        );
        eprintln!("Scale factor: {}", reconstructed[0] / input[0]);
    }

    #[test]
    #[ignore] // IDCT scaling needs calibration - see NOTE in IDCT section
    fn test_idct_8x8_roundtrip() {
        use super::{dct_8x8, idct_8x8};

        // Random-ish input
        let input: [f32; 64] = core::array::from_fn(|i| ((i as f32 * 0.7).sin() + 0.5) * 100.0);

        let mut coeffs = [0.0f32; 64];
        let mut reconstructed = [0.0f32; 64];

        dct_8x8(&input, &mut coeffs);
        idct_8x8(&coeffs, &mut reconstructed);

        // Verify roundtrip
        let mut max_err = 0.0f32;
        for i in 0..64 {
            let err = (input[i] - reconstructed[i]).abs();
            max_err = max_err.max(err);
        }
        eprintln!("Roundtrip max error: {}", max_err);
        eprintln!(
            "Input[0]: {}, Reconstructed[0]: {}",
            input[0], reconstructed[0]
        );
        eprintln!("Scale factor needed: {}", reconstructed[0] / input[0]);
        assert!(
            max_err < 1e-3,
            "idct_8x8 roundtrip max error {} too large",
            max_err
        );
    }

    #[test]
    fn test_identity_roundtrip() {
        // Random-ish 8x8 pixel block
        let pixels: [f32; 64] = core::array::from_fn(|i| ((i as f32 * 1.3).sin() + 0.5) * 200.0);

        let mut coeffs = [0.0f32; 64];
        identity_transform(&pixels, 8, &mut coeffs);

        let mut reconstructed = [0.0f32; 64];
        inverse_identity_transform(&coeffs, &mut reconstructed);

        let mut max_err = 0.0f32;
        for i in 0..64 {
            let err = (pixels[i] - reconstructed[i]).abs();
            if err > max_err {
                max_err = err;
            }
        }
        assert!(
            max_err < 1e-4,
            "identity roundtrip max error {} too large",
            max_err
        );
    }

    #[test]
    fn test_identity_roundtrip_constant() {
        // Constant block: all pixels the same
        let pixels = [42.0f32; 64];

        let mut coeffs = [0.0f32; 64];
        identity_transform(&pixels, 8, &mut coeffs);

        let mut reconstructed = [0.0f32; 64];
        inverse_identity_transform(&coeffs, &mut reconstructed);

        let mut max_err = 0.0f32;
        for i in 0..64 {
            let err = (pixels[i] - reconstructed[i]).abs();
            max_err = max_err.max(err);
        }
        assert!(
            max_err < 1e-4,
            "identity roundtrip (constant) max error {} too large",
            max_err
        );
    }

    #[test]
    fn test_dct2x2_roundtrip() {
        // Random-ish 8x8 pixel block
        let pixels: [f32; 64] = core::array::from_fn(|i| ((i as f32 * 0.9).cos() + 1.0) * 128.0);

        let mut coeffs = [0.0f32; 64];
        dct2x2_transform(&pixels, 8, &mut coeffs);

        let mut reconstructed = [0.0f32; 64];
        inverse_dct2x2_transform(&coeffs, &mut reconstructed);

        let mut max_err = 0.0f32;
        for i in 0..64 {
            let err = (pixels[i] - reconstructed[i]).abs();
            if err > max_err {
                max_err = err;
            }
        }
        assert!(
            max_err < 1e-4,
            "dct2x2 roundtrip max error {} too large",
            max_err
        );
    }

    #[test]
    fn test_dct2x2_roundtrip_constant() {
        let pixels = [99.0f32; 64];

        let mut coeffs = [0.0f32; 64];
        dct2x2_transform(&pixels, 8, &mut coeffs);

        let mut reconstructed = [0.0f32; 64];
        inverse_dct2x2_transform(&coeffs, &mut reconstructed);

        let mut max_err = 0.0f32;
        for i in 0..64 {
            let err = (pixels[i] - reconstructed[i]).abs();
            max_err = max_err.max(err);
        }
        assert!(
            max_err < 1e-4,
            "dct2x2 roundtrip (constant) max error {} too large",
            max_err
        );
    }
}
