//! Smart-dispatch follow-on to W22-1 / W23-2 — zenanalyze-driven
//! `screenshot_lift_hint`.
//!
//! W22-1 (`9dcb8394`) shipped opt-in `with_content_aware_entropy_mul`
//! that lifts the IDENTITY/DCT2x2/AFV/DCT4x8 `entropy_mul` table when
//! `median(mask1x1) > 95`.  W23-2 (`68c74ef3`) ran a 465-cell bisect
//! and honest-stopped: every lifted tuple regressed `windows95.png`
//! (14-color pixel-art / palette content) by +30-33% butteraugli at
//! d=0.5 — the mask1x1 discriminator is too coarse.
//!
//! Chunk-1 hypothesis: zenanalyze Tier-1 features cleanly separate
//! windows95.png from the other 9 gb82-sc screenshots that benefit
//! from the lift.  See the exploration log at
//! `~/.claude/projects/-home-lilith-work-zen-jxl-encoder/memory/MEMORY.md`
//! ("W22-1 honest-stop entry") — windows95 sits 2-7× outside the
//! main cluster on `palette_log2_size`, `edge_density`,
//! `high_freq_energy_ratio`, and `flat_color_block_ratio`.
//!
//! Classifier rule (chunk-1, intentionally simple — 1 feature):
//!     screenshot AND palette_log2_size >= 7  → lift = Some(true)
//!     screenshot AND palette_log2_size <= 6  → lift = Some(false)
//!     non-screenshot                          → no opt-in
//!
//! `palette_log2_size = 4` for windows95, `>= 8` for every other
//! gb82-sc screenshot in the W23-2 set.  A single threshold separates
//! the wins from the regression with margin to spare.
//!
//! ## Run
//!
//! ```ignore
//! # Temporary edits to jxl-encoder/Cargo.toml — DO NOT commit:
//! #   [dev-dependencies]
//! #   zenanalyze = { path = "../../zenanalyze", features = ["experimental"] }
//! # plus an autogenerated [[example]] block isn't needed — cargo picks up
//! # examples/*.rs automatically.
//! cargo run -p jxl-encoder --release --example entropy_mul_smart_dispatch_ab \
//!     --features '__expert butteraugli-loop parallel' -- \
//!     [benchmarks/entropy_mul_smart_dispatch_2026-05-18.tsv]
//! ```
//!
//! ## Output
//!
//! Per (image, distance) two rows in the TSV — `smart_off` baseline
//! (libjxl-faithful reference table) and `smart_on` (lifted table iff
//! classifier predicts "safe to lift").  Deltas reported on the
//! `smart_on` row.
//!
//! ## Decision rule (from the task spec)
//!
//! - **Pass**: avg screen-class bytes Δ ≤ -0.3 % AND no individual
//!   cell shows `|bfly Δ| > 3 %`.
//! - **Fail**: honest-stop and document.

use butteraugli::{ButteraugliParams, butteraugli_linear, srgb_to_linear};
use image::GenericImageView;
use imgref::Img;
use jxl_encoder::{LossyConfig, PixelLayout};
use rgb::RGB;
use std::io::Cursor;
use std::path::PathBuf;
use std::time::Instant;
use zenanalyze::analyze_features_rgb8;
use zenanalyze::feature::{AnalysisFeature, AnalysisQuery, FeatureSet};

const DISTANCES: &[f32] = &[0.5, 1.0, 2.0];
const EFFORT: u8 = 7;
/// Discriminator threshold on `palette_log2_size`. Images with
/// `palette_log2_size <= LIFT_PALETTE_MIN_LOG2` are flagged
/// `lift = Some(false)` (windows95-class — palette / pixel-art that
/// regresses under the lifted entropy_mul table).  `>= 7` (>= 64
/// distinct colour bins) ⇒ continuous-tone screen content that
/// benefits from the lift.
const LIFT_PALETTE_MIN_LOG2: u32 = 6;

struct Source {
    label: &'static str,
    class: &'static str,
    path: PathBuf,
}

fn decode_jxl_linear(bytes: &[u8]) -> Option<(usize, usize, Vec<f32>)> {
    let reader = Cursor::new(bytes);
    let mut img = jxl_oxide::JxlImage::builder().read(reader).ok()?;
    img.request_color_encoding(jxl_oxide::EnumColourEncoding::srgb_linear(
        jxl_oxide::RenderingIntent::Relative,
    ));
    let render = img.render_frame(0).ok()?;
    let fb = render.image_all_channels();
    Some((fb.width(), fb.height(), fb.buf().to_vec()))
}

fn linear_to_srgb_u8(linear: f32) -> u8 {
    let c = linear.clamp(0.0, 1.0);
    let srgb = if c <= 0.003_130_8 {
        12.92 * c
    } else {
        1.055 * c.powf(1.0 / 2.4) - 0.055
    };
    (srgb * 255.0).round() as u8
}

/// Returns `(plog2, fcbr, edge_density, classify_ms, lift_hint)`.
///
/// `lift_hint` is `Some(true)` iff the image is screenshot-class
/// (high `flat_color_block_ratio` + `uniformity`) AND has enough
/// distinct colours (`palette_log2_size > LIFT_PALETTE_MIN_LOG2`)
/// to be continuous-tone screen content.  `Some(false)` for
/// screenshots-with-tiny-palette (windows95-class).  `None` for
/// non-screenshot content — falls back to the encoder-internal
/// `median(mask1x1) > 95` check (W22-1 default).
fn classify(rgb: &[u8], w: u32, h: u32) -> (u32, f32, f32, f64, Option<bool>) {
    let needed = FeatureSet::new()
        .with(AnalysisFeature::PaletteLog2Size)
        .with(AnalysisFeature::FlatColorBlockRatio)
        .with(AnalysisFeature::Uniformity)
        .with(AnalysisFeature::EdgeDensity);
    let q = AnalysisQuery::new(needed);
    let t0 = Instant::now();
    let res = analyze_features_rgb8(rgb, w, h, &q);
    let elapsed_ms = t0.elapsed().as_secs_f64() * 1000.0;
    let plog2 = res
        .get(AnalysisFeature::PaletteLog2Size)
        .and_then(|v| v.as_u32())
        .unwrap_or(0);
    let fcbr = res
        .get(AnalysisFeature::FlatColorBlockRatio)
        .and_then(|v| v.as_f32())
        .unwrap_or(0.0);
    let unif = res
        .get(AnalysisFeature::Uniformity)
        .and_then(|v| v.as_f32())
        .unwrap_or(0.0);
    let edge = res
        .get(AnalysisFeature::EdgeDensity)
        .and_then(|v| v.as_f32())
        .unwrap_or(0.0);

    // Two-stage classifier:
    //   1. `palette_log2_size <= LIFT_PALETTE_MIN_LOG2` (pixel-art /
    //      palette content like windows95) → force `lift = Some(false)`
    //      regardless of whether the image otherwise looks "screen".
    //      The mask1x1 fallback (W22-1) fires on windows95 too, so the
    //      explicit suppress is needed to keep the encoder on the
    //      reference table.
    //   2. Otherwise, if `flat_color_block_ratio >= 0.50` and
    //      `uniformity >= 0.50` (continuous-tone screen content) →
    //      `lift = Some(true)`.
    //   3. Anything else (photo / mixed) → `lift = None`, falls back
    //      to the encoder-internal mask1x1 discriminator (which is
    //      already photo-safe — `median(mask1x1) > 95` rarely fires
    //      on photos).
    let lift = if plog2 <= LIFT_PALETTE_MIN_LOG2 {
        Some(false)
    } else if fcbr >= 0.50 && unif >= 0.50 {
        Some(true)
    } else {
        None
    };
    (plog2, fcbr, edge, elapsed_ms, lift)
}

fn encode(
    rgb_u8: &[u8],
    w: u32,
    h: u32,
    d: f32,
    smart_on: bool,
    lift_hint: Option<bool>,
) -> Result<Vec<u8>, String> {
    let mut cfg = LossyConfig::new(d).with_effort(EFFORT);
    if smart_on {
        cfg = cfg
            .with_content_aware_entropy_mul(true)
            .with_strategy_overrides(jxl_encoder::api::StrategyOverrides { screenshot_lift_hint: lift_hint, ..Default::default() });
    }
    cfg.encode(rgb_u8, w, h, PixelLayout::Rgb8)
        .map_err(|e| format!("encode failed: {e:?}"))
}

#[derive(Debug, Clone, Copy)]
struct Measure {
    bytes: usize,
    butteraugli: f64,
    ssim2: f64,
    encode_ms: f64,
}

#[allow(clippy::too_many_arguments)]
fn measure(
    rgb_u8: &[u8],
    w: u32,
    h: u32,
    d: f32,
    smart_on: bool,
    lift_hint: Option<bool>,
    orig_linear_img: &Img<Vec<RGB<f32>>>,
    orig_srgb_img: &Img<Vec<[u8; 3]>>,
    params: &ButteraugliParams,
) -> Result<Measure, String> {
    let t0 = Instant::now();
    let bytes = encode(rgb_u8, w, h, d, smart_on, lift_hint)?;
    let encode_ms = t0.elapsed().as_secs_f64() * 1000.0;

    let (dw, dh, decoded_linear) =
        decode_jxl_linear(&bytes).ok_or_else(|| "decode failed".to_string())?;
    if dw != w as usize || dh != h as usize {
        return Err(format!("decoded {dw}x{dh} ≠ {w}x{h}"));
    }
    let dec_pixels: Vec<RGB<f32>> = decoded_linear
        .chunks(3)
        .map(|c| RGB::new(c[0], c[1], c[2]))
        .collect();
    let dec_linear_img = Img::new(dec_pixels, dw, dh);
    let bfly = butteraugli_linear(orig_linear_img.as_ref(), dec_linear_img.as_ref(), params)
        .map(|r| r.score)
        .unwrap_or(f64::NAN);
    let dec_srgb: Vec<[u8; 3]> = decoded_linear
        .chunks(3)
        .map(|c| {
            [
                linear_to_srgb_u8(c[0]),
                linear_to_srgb_u8(c[1]),
                linear_to_srgb_u8(c[2]),
            ]
        })
        .collect();
    let dec_srgb_img = Img::new(dec_srgb, dw, dh);
    let ssim2 = fast_ssim2::compute_ssimulacra2(orig_srgb_img.as_ref(), dec_srgb_img.as_ref())
        .unwrap_or(f64::NAN);

    Ok(Measure {
        bytes: bytes.len(),
        butteraugli: bfly,
        ssim2,
        encode_ms,
    })
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let out_path = args
        .into_iter()
        .next()
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            PathBuf::from("benchmarks/entropy_mul_smart_dispatch_2026-05-18.tsv")
        });

    let corpus = PathBuf::from(
        std::env::var("CODEC_CORPUS_DIR")
            .unwrap_or_else(|_| String::from("/home/lilith/work/codec-corpus")),
    );

    // All 10 gb82-sc screenshots — the same set the chunk-1 zenanalyze
    // exploration scored.  windows95 is the W23-2 honest-stop case;
    // the remaining 9 are the lift wins the smart dispatch is
    // designed to keep.
    let sources = vec![
        Source {
            label: "gb82/codec_wiki",
            class: "screen",
            path: corpus.join("gb82-sc/codec_wiki.png"),
        },
        Source {
            label: "gb82/gmessages",
            class: "screen",
            path: corpus.join("gb82-sc/gmessages.png"),
        },
        Source {
            label: "gb82/graph",
            class: "screen",
            path: corpus.join("gb82-sc/graph.png"),
        },
        Source {
            label: "gb82/gui",
            class: "screen",
            path: corpus.join("gb82-sc/gui.png"),
        },
        Source {
            label: "gb82/imac_dark",
            class: "screen",
            path: corpus.join("gb82-sc/imac_dark.png"),
        },
        Source {
            label: "gb82/imac_g3",
            class: "screen",
            path: corpus.join("gb82-sc/imac_g3.png"),
        },
        Source {
            label: "gb82/imessage",
            class: "screen",
            path: corpus.join("gb82-sc/imessage.png"),
        },
        Source {
            label: "gb82/terminal",
            class: "screen",
            path: corpus.join("gb82-sc/terminal.png"),
        },
        Source {
            label: "gb82/windows",
            class: "screen",
            path: corpus.join("gb82-sc/windows.png"),
        },
        Source {
            label: "gb82/windows95",
            class: "screen",
            path: corpus.join("gb82-sc/windows95.png"),
        },
    ];

    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent).ok();
    }
    let staging = PathBuf::from(format!(
        "/tmp/entropy_mul_smart_dispatch_ab_{}.tsv",
        std::process::id()
    ));
    let mut out = std::fs::File::create(&staging).expect("create staging tsv");
    use std::io::Write;
    writeln!(
        out,
        "image\tclass\tdistance\tmode\tplog2\tfcbr\tedge_density\tlift_hint\tclass_ms\tbytes\tbutteraugli\tssim2\tencode_ms\tbytes_delta_pct\tbfly_delta_pct\tssim2_delta_abs"
    )
    .unwrap();

    let params = ButteraugliParams::default();

    for src in &sources {
        if !src.path.exists() {
            eprintln!("MISS {}", src.path.display());
            continue;
        }
        let img = match image::open(&src.path) {
            Ok(i) => i,
            Err(e) => {
                eprintln!("open {}: {e}", src.path.display());
                continue;
            }
        };
        let (w, h) = img.dimensions();
        let rgb = img.to_rgb8();
        let rgb_u8: &[u8] = rgb.as_raw();

        let (plog2, fcbr, edge, class_ms, lift_hint) = classify(rgb_u8, w, h);
        eprintln!(
            "=== {} ({}, {}x{})  plog2={} fcbr={:.3} edge={:.4} class_ms={:.2}  lift_hint={:?} ===",
            src.label, src.class, w, h, plog2, fcbr, edge, class_ms, lift_hint
        );

        // Pre-build references once per image.
        let linear_rgb: Vec<f32> = rgb
            .pixels()
            .flat_map(|p| {
                [
                    srgb_to_linear(p[0]),
                    srgb_to_linear(p[1]),
                    srgb_to_linear(p[2]),
                ]
            })
            .collect();
        let orig_pixels: Vec<RGB<f32>> = linear_rgb
            .chunks(3)
            .map(|c| RGB::new(c[0], c[1], c[2]))
            .collect();
        let orig_linear_img = Img::new(orig_pixels, w as usize, h as usize);
        let orig_srgb_pixels: Vec<[u8; 3]> =
            rgb.pixels().map(|p| [p[0], p[1], p[2]]).collect();
        let orig_srgb_img = Img::new(orig_srgb_pixels, w as usize, h as usize);

        for &d in DISTANCES {
            let m_off = match measure(
                rgb_u8,
                w,
                h,
                d,
                false,
                None,
                &orig_linear_img,
                &orig_srgb_img,
                &params,
            ) {
                Ok(m) => m,
                Err(e) => {
                    eprintln!("  smart_off d={d}: {e}");
                    continue;
                }
            };
            let m_on = match measure(
                rgb_u8,
                w,
                h,
                d,
                true,
                lift_hint,
                &orig_linear_img,
                &orig_srgb_img,
                &params,
            ) {
                Ok(m) => m,
                Err(e) => {
                    eprintln!("  smart_on  d={d}: {e}");
                    continue;
                }
            };

            let bytes_delta_pct =
                (m_on.bytes as f64 - m_off.bytes as f64) / m_off.bytes as f64 * 100.0;
            let bfly_delta_pct =
                (m_on.butteraugli - m_off.butteraugli) / m_off.butteraugli.max(1e-9) * 100.0;
            let ssim2_delta_abs = m_on.ssim2 - m_off.ssim2;

            writeln!(
                out,
                "{}\t{}\t{:.3}\tsmart_off\t{}\t{:.4}\t{:.4}\t{:?}\t{:.2}\t{}\t{:.4}\t{:.4}\t{:.2}\t\t\t",
                src.label,
                src.class,
                d,
                plog2,
                fcbr,
                edge,
                lift_hint,
                class_ms,
                m_off.bytes,
                m_off.butteraugli,
                m_off.ssim2,
                m_off.encode_ms,
            )
            .unwrap();
            writeln!(
                out,
                "{}\t{}\t{:.3}\tsmart_on\t{}\t{:.4}\t{:.4}\t{:?}\t{:.2}\t{}\t{:.4}\t{:.4}\t{:.2}\t{:+.3}\t{:+.3}\t{:+.4}",
                src.label,
                src.class,
                d,
                plog2,
                fcbr,
                edge,
                lift_hint,
                class_ms,
                m_on.bytes,
                m_on.butteraugli,
                m_on.ssim2,
                m_on.encode_ms,
                bytes_delta_pct,
                bfly_delta_pct,
                ssim2_delta_abs,
            )
            .unwrap();
            out.flush().unwrap();
            eprintln!(
                "  d={d} OFF: {}B bfly={:.4} ssim2={:.4} {:.0}ms",
                m_off.bytes, m_off.butteraugli, m_off.ssim2, m_off.encode_ms,
            );
            eprintln!(
                "       ON: {}B bfly={:.4} ssim2={:.4} {:.0}ms  Δbytes={:+.2}% Δbfly={:+.2}% Δssim2={:+.3}",
                m_on.bytes,
                m_on.butteraugli,
                m_on.ssim2,
                m_on.encode_ms,
                bytes_delta_pct,
                bfly_delta_pct,
                ssim2_delta_abs
            );
        }
    }

    drop(out);
    std::fs::rename(&staging, &out_path).expect("atomic mv staging → out_path");
    eprintln!("\nTSV: {}", out_path.display());
}
