#!/usr/bin/env python3
"""
Compare cjxl-rs metrics against cjxl reference CSV.

Usage:
    python3 scripts/rd_report.py [--effort 5|6|7|8] [--quick]

Reads:
    reference/cjxl_reference.csv  (committed, generated by generate_cjxl_reference.sh)
    reference/cjxl_rs_latest.csv  (gitignored, generated by measure_cjxl_rs.sh)

Prints:
    1. Aggregate table by corpus x distance (size delta %, SSIM2 delta, butteraugli delta)
    2. Worst/best 5 images per distance
    3. Grand summary
    4. Timing comparison
"""

import csv
import sys
import argparse
from collections import defaultdict
from pathlib import Path


def load_csv(path):
    """Load a metrics CSV, skipping comment lines."""
    rows = []
    with open(path, newline="") as f:
        for line in f:
            if line.startswith("#"):
                continue
            break
        # Re-read from beginning, skipping comments
        f.seek(0)
        lines = [l for l in f if not l.startswith("#")]
    reader = csv.DictReader(lines)
    for row in reader:
        rows.append(row)
    return rows


def main():
    parser = argparse.ArgumentParser(description="RD comparison report")
    parser.add_argument(
        "--effort", type=int, default=7, choices=[5, 6, 7, 8],
        help="cjxl effort level to compare against (default: 7)"
    )
    parser.add_argument(
        "--quick", action="store_true",
        help="Only report on images present in cjxl_rs_latest.csv"
    )
    args = parser.parse_args()

    ref_path = Path("reference/cjxl_reference.csv")
    rs_path = Path("reference/cjxl_rs_latest.csv")

    if not ref_path.exists():
        print(f"ERROR: {ref_path} not found. Run: just generate-reference", file=sys.stderr)
        sys.exit(1)
    if not rs_path.exists():
        print(f"ERROR: {rs_path} not found. Run: just rd-compare", file=sys.stderr)
        sys.exit(1)

    ref_rows = load_csv(ref_path)
    rs_rows = load_csv(rs_path)

    # Index reference by (corpus, image, distance, effort)
    ref_index = {}
    for row in ref_rows:
        key = (row["corpus"], row["image"], row["distance"], row["effort"])
        ref_index[key] = row

    # Index cjxl-rs by (corpus, image, distance)
    rs_index = {}
    for row in rs_rows:
        key = (row["corpus"], row["image"], row["distance"])
        rs_index[key] = row

    effort = str(args.effort)

    # Collect comparisons
    comparisons = []  # list of dicts with deltas
    for (corpus, image, dist), rs_row in rs_index.items():
        ref_key = (corpus, image, dist, effort)
        ref_row = ref_index.get(ref_key)
        if ref_row is None:
            continue

        ref_size = int(ref_row["size_bytes"])
        rs_size = int(rs_row["size_bytes"])
        ref_ssim2 = float(ref_row["ssimulacra2"])
        rs_ssim2 = float(rs_row["ssimulacra2"])
        ref_bfly = float(ref_row["butteraugli"])
        rs_bfly = float(rs_row["butteraugli"])

        size_pct = (rs_size - ref_size) / ref_size * 100 if ref_size > 0 else 0

        # Timing (may not be present in older CSVs)
        ref_wall = float(ref_row.get("enc_wall_s", 0))
        rs_wall = float(rs_row.get("enc_wall_s", 0))

        comparisons.append({
            "corpus": corpus,
            "image": image,
            "distance": float(dist),
            "ref_size": ref_size,
            "rs_size": rs_size,
            "size_pct": size_pct,
            "ref_ssim2": ref_ssim2,
            "rs_ssim2": rs_ssim2,
            "ssim2_delta": rs_ssim2 - ref_ssim2,
            "ref_bfly": ref_bfly,
            "rs_bfly": rs_bfly,
            "bfly_delta": rs_bfly - ref_bfly,
            "ref_wall": ref_wall,
            "rs_wall": rs_wall,
        })

    if not comparisons:
        print("No matching comparisons found. Check that both CSVs have overlapping images/distances.")
        sys.exit(1)

    # ── Section 1: Aggregate by corpus × distance ──
    print(f"\n{'='*80}")
    print(f"  cjxl-rs vs cjxl e{effort}  ({len(comparisons)} comparisons)")
    print(f"{'='*80}")

    # Group by (corpus, distance)
    groups = defaultdict(list)
    for c in comparisons:
        groups[(c["corpus"], c["distance"])].append(c)

    # Also track by distance only (for TOTAL row)
    by_dist = defaultdict(list)
    for c in comparisons:
        by_dist[c["distance"]].append(c)

    distances = sorted(set(c["distance"] for c in comparisons))
    corpora = sorted(set(c["corpus"] for c in comparisons))

    # Header
    print(f"\n{'Corpus':<10} {'Dist':>5} {'N':>4}  {'Size Δ%':>8} {'SSIM2 Δ':>8} {'Bfly Δ':>8}  {'RS wall':>8} {'Ref wall':>8}")
    print("-" * 80)

    for dist in distances:
        for corpus in corpora:
            items = groups.get((corpus, dist), [])
            if not items:
                continue
            n = len(items)
            avg_size_pct = sum(c["size_pct"] for c in items) / n
            avg_ssim2_d = sum(c["ssim2_delta"] for c in items) / n
            avg_bfly_d = sum(c["bfly_delta"] for c in items) / n
            avg_rs_wall = sum(c["rs_wall"] for c in items) / n
            avg_ref_wall = sum(c["ref_wall"] for c in items) / n

            size_str = f"{avg_size_pct:+.1f}%"
            ssim_str = f"{avg_ssim2_d:+.2f}"
            bfly_str = f"{avg_bfly_d:+.3f}"
            rs_t = f"{avg_rs_wall:.2f}s"
            ref_t = f"{avg_ref_wall:.2f}s"

            print(f"{corpus:<10} {dist:>5.2f} {n:>4}  {size_str:>8} {ssim_str:>8} {bfly_str:>8}  {rs_t:>8} {ref_t:>8}")

        # TOTAL for this distance
        items = by_dist[dist]
        n = len(items)
        avg_size_pct = sum(c["size_pct"] for c in items) / n
        avg_ssim2_d = sum(c["ssim2_delta"] for c in items) / n
        avg_bfly_d = sum(c["bfly_delta"] for c in items) / n
        avg_rs_wall = sum(c["rs_wall"] for c in items) / n
        avg_ref_wall = sum(c["ref_wall"] for c in items) / n

        size_str = f"{avg_size_pct:+.1f}%"
        ssim_str = f"{avg_ssim2_d:+.2f}"
        bfly_str = f"{avg_bfly_d:+.3f}"
        rs_t = f"{avg_rs_wall:.2f}s"
        ref_t = f"{avg_ref_wall:.2f}s"

        print(f"{'TOTAL':<10} {dist:>5.2f} {n:>4}  {size_str:>8} {ssim_str:>8} {bfly_str:>8}  {rs_t:>8} {ref_t:>8}")
        print("-" * 80)

    # ── Section 2: Worst/best 5 per distance ──
    print(f"\n{'='*80}")
    print("  Outliers: worst/best 5 by size delta %")
    print(f"{'='*80}")

    for dist in distances:
        items = by_dist[dist]
        sorted_by_size = sorted(items, key=lambda c: c["size_pct"])

        print(f"\n  d={dist:.2f}:")

        # Best 5 (most negative = smallest relative to ref)
        print(f"    Best (smaller than cjxl e{effort}):")
        for c in sorted_by_size[:5]:
            print(f"      {c['corpus']}/{c['image']}  size:{c['size_pct']:+.1f}%  "
                  f"ssim2:{c['ssim2_delta']:+.2f}  bfly:{c['bfly_delta']:+.3f}")

        # Worst 5 (most positive = largest relative to ref)
        print(f"    Worst (larger than cjxl e{effort}):")
        for c in sorted_by_size[-5:]:
            print(f"      {c['corpus']}/{c['image']}  size:{c['size_pct']:+.1f}%  "
                  f"ssim2:{c['ssim2_delta']:+.2f}  bfly:{c['bfly_delta']:+.3f}")

    # ── Section 3: Grand summary ──
    print(f"\n{'='*80}")
    print("  Grand Summary")
    print(f"{'='*80}")

    n = len(comparisons)
    avg_size = sum(c["size_pct"] for c in comparisons) / n
    avg_ssim2 = sum(c["ssim2_delta"] for c in comparisons) / n
    avg_bfly = sum(c["bfly_delta"] for c in comparisons) / n
    med_size = sorted(c["size_pct"] for c in comparisons)[n // 2]

    total_ref_bytes = sum(c["ref_size"] for c in comparisons)
    total_rs_bytes = sum(c["rs_size"] for c in comparisons)
    total_size_pct = (total_rs_bytes - total_ref_bytes) / total_ref_bytes * 100

    wins_size = sum(1 for c in comparisons if c["size_pct"] < 0)
    wins_ssim2 = sum(1 for c in comparisons if c["ssim2_delta"] > 0)
    wins_bfly = sum(1 for c in comparisons if c["bfly_delta"] < 0)

    print(f"\n  Comparisons:    {n}")
    print(f"  vs cjxl effort: {effort}")
    print(f"")
    print(f"  Avg size Δ:     {avg_size:+.2f}%  (median {med_size:+.2f}%)")
    print(f"  Total bytes Δ:  {total_size_pct:+.2f}%  ({total_rs_bytes:,} vs {total_ref_bytes:,})")
    print(f"  Avg SSIM2 Δ:    {avg_ssim2:+.3f}")
    print(f"  Avg Bfly Δ:     {avg_bfly:+.4f}")
    print(f"")
    print(f"  Wins (size):    {wins_size}/{n} ({wins_size/n*100:.0f}%)")
    print(f"  Wins (ssim2):   {wins_ssim2}/{n} ({wins_ssim2/n*100:.0f}%)")
    print(f"  Wins (bfly):    {wins_bfly}/{n} ({wins_bfly/n*100:.0f}%)")

    # Timing summary
    total_rs_wall = sum(c["rs_wall"] for c in comparisons)
    total_ref_wall = sum(c["ref_wall"] for c in comparisons)
    if total_ref_wall > 0:
        print(f"")
        print(f"  Total encode time:")
        print(f"    cjxl-rs:      {total_rs_wall:.1f}s")
        print(f"    cjxl e{effort}:     {total_ref_wall:.1f}s")
        print(f"    Ratio:        {total_rs_wall/total_ref_wall:.2f}x")

    print()


if __name__ == "__main__":
    main()
